import { buildWorldSceneGallery, type StockKind } from './worldsceneImageLibrary';

export type TravelMode = 'drive' | 'bus' | 'walk' | 'bike';

export interface DestinationPoint {
  id: string;
  name: string;
  englishName: string;
  aliases: string[];
  country: string;
  city: string;
  region: string;
  category: '自然景观' | '人文古迹' | '城市地标' | '海岛度假';
  grade: '普通' | '精品' | '5A';
  lat: number;
  lng: number;
  tagline: string;
  description: string;
  bestSeason: string;
  tags: string[];
  highlights: string[];
  images: string[];
  ticketCny: number;
  stayCny: number;
  mealCny: number;
}

export interface OriginPreset {
  id: string;
  city: string;
  lat: number;
  lng: number;
  budgetBand: 'low' | 'medium' | 'high';
}

const wmCard = (pointId: string, kind: StockKind) => buildWorldSceneGallery(pointId, kind);

export const DESTINATION_POINTS: readonly DestinationPoint[] = [
  {
    id: 'forbidden-city',
    name: '故宫',
    englishName: 'The Forbidden City',
    aliases: ['紫禁城', '北京故宫', '中国故宫'],
    country: '中国',
    city: '北京',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 39.9163,
    lng: 116.3972,
    tagline: '东方皇家宫殿群与中轴线叙事的代表性目的地',
    description: '明清皇宫建筑群，适合从文化遗产、建筑轴线和城市历史切入浏览。',
    bestSeason: '4-5 月 / 9-10 月',
    tags: ['皇家建筑', '中式古迹', '博物馆'],
    highlights: ['太和殿', '神武门', '角楼'],
    images: wmCard('forbidden-city', 'heritage'),
    ticketCny: 80,
    stayCny: 420,
    mealCny: 180,
  },
  {
    id: 'great-wall',
    name: '长城',
    englishName: 'The Great Wall',
    aliases: ['万里长城', '中国长城', '慕田峪长城'],
    country: '中国',
    city: '北京',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 40.4319,
    lng: 116.5704,
    tagline: '山脊防御体系与东方工程奇观交织而成的历史景观',
    description: '世界级线性遗产，适合搭配山地地形与历史防御路线可视化。',
    bestSeason: '4-6 月 / 9-11 月',
    tags: ['世界遗产', '山地古迹', '历史防线'],
    highlights: ['慕田峪段', '八达岭', '司马台'],
    images: wmCard('great-wall', 'heritage'),
    ticketCny: 140,
    stayCny: 380,
    mealCny: 160,
  },
  {
    id: 'terracotta-army',
    name: '秦始皇兵马俑',
    englishName: 'Terracotta Army',
    aliases: ['兵马俑', '秦兵马俑', '西安兵马俑'],
    country: '中国',
    city: '西安',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 34.3849,
    lng: 109.2732,
    tagline: '地下军阵与帝国叙事结合的考古级文化地标',
    description: '以考古发现和兵马阵列著称，适合展示文明遗产与博物馆型景点。',
    bestSeason: '3-5 月 / 9-11 月',
    tags: ['考古', '历史', '博物馆'],
    highlights: ['一号坑', '铜车马', '考古陈列'],
    images: wmCard('terracotta-army', 'heritage'),
    ticketCny: 120,
    stayCny: 300,
    mealCny: 140,
  },
  {
    id: 'mount-fuji',
    name: '富士山',
    englishName: 'Mount Fuji',
    aliases: ['日本富士山', '富士', 'Fuji'],
    country: '日本',
    city: '静冈',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 35.3606,
    lng: 138.7274,
    tagline: '雪顶火山与湖面倒影构成日本最具识别度的自然名片',
    description: '火山轮廓、湖景和四季气候变化明显，适合自然地标类浏览。',
    bestSeason: '11-2 月 / 7-8 月',
    tags: ['火山', '雪山', '摄影'],
    highlights: ['河口湖', '五合目', '新仓山浅间公园'],
    images: wmCard('mount-fuji', 'nature'),
    ticketCny: 0,
    stayCny: 480,
    mealCny: 220,
  },
  {
    id: 'kyoto',
    name: '京都',
    englishName: 'Kyoto',
    aliases: ['日本京都', '古都京都'],
    country: '日本',
    city: '京都',
    region: '亚洲',
    category: '人文古迹',
    grade: '精品',
    lat: 35.0116,
    lng: 135.7681,
    tagline: '古都街巷与四季寺院景观交叠的文化目的地',
    description: '寺院、庭园和町屋街区密集，适合文化沉浸和慢旅行路线。',
    bestSeason: '3-5 月 / 10-11 月',
    tags: ['古都', '寺院', '城市漫游'],
    highlights: ['清水寺', '伏见稻荷', '岚山竹林'],
    images: wmCard('kyoto', 'heritage'),
    ticketCny: 120,
    stayCny: 560,
    mealCny: 240,
  },
  {
    id: 'angkor-wat',
    name: '吴哥窟',
    englishName: 'Angkor Wat',
    aliases: ['柬埔寨吴哥窟', 'Angkor'],
    country: '柬埔寨',
    city: '暹粒',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 13.4125,
    lng: 103.867,
    tagline: '热带丛林中的高棉寺庙群呈现宏大的石刻文明景观',
    description: '适合展示遗址群分布、日出视角和宗教建筑主题。',
    bestSeason: '11-2 月',
    tags: ['寺庙群', '世界遗产', '日出'],
    highlights: ['吴哥寺', '巴戎寺', '塔普伦寺'],
    images: wmCard('angkor-wat', 'heritage'),
    ticketCny: 260,
    stayCny: 260,
    mealCny: 110,
  },
  {
    id: 'taj-mahal',
    name: '泰姬陵',
    englishName: 'Taj Mahal',
    aliases: ['印度泰姬陵', '阿格拉泰姬陵'],
    country: '印度',
    city: '阿格拉',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 27.1751,
    lng: 78.0421,
    tagline: '白色陵墓与对称园林构成古典爱情地标',
    description: '适合以建筑对称、庭园轴线和世界遗产身份进行展示。',
    bestSeason: '11-2 月',
    tags: ['爱情地标', '白色建筑', '世界遗产'],
    highlights: ['主陵墓', '倒影池', '亚穆纳河观景点'],
    images: wmCard('taj-mahal', 'heritage'),
    ticketCny: 220,
    stayCny: 280,
    mealCny: 100,
  },
  {
    id: 'petra',
    name: '佩特拉',
    englishName: 'Petra',
    aliases: ['约旦佩特拉', '玫瑰古城'],
    country: '约旦',
    city: '瓦迪穆萨',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 30.3285,
    lng: 35.4444,
    tagline: '峡谷尽头的岩壁古城拥有极强的沉浸式进入感',
    description: '沙岩峡谷与古城立面结合，适合路线式探索和遗迹类点位展示。',
    bestSeason: '3-5 月 / 9-11 月',
    tags: ['峡谷古城', '遗迹', '沙岩'],
    highlights: ['卡兹尼神殿', '修道院', '蛇道'],
    images: wmCard('petra', 'heritage'),
    ticketCny: 480,
    stayCny: 340,
    mealCny: 130,
  },
  {
    id: 'cappadocia',
    name: '卡帕多奇亚',
    englishName: 'Cappadocia',
    aliases: ['土耳其热气球', '土耳其卡帕多奇亚'],
    country: '土耳其',
    city: '内夫谢希尔',
    region: '亚洲',
    category: '自然景观',
    grade: '精品',
    lat: 38.6431,
    lng: 34.827,
    tagline: '热气球、岩层地貌与洞穴聚落构成的奇幻地表',
    description: '适合呈现地貌类目的地与低空飞行体验的结合浏览。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['热气球', '地貌', '摄影'],
    highlights: ['格雷梅', '热气球观景', '地下城'],
    images: wmCard('cappadocia', 'nature'),
    ticketCny: 120,
    stayCny: 420,
    mealCny: 150,
  },
  {
    id: 'ha-long-bay',
    name: '下龙湾',
    englishName: 'Ha Long Bay',
    aliases: ['越南下龙湾'],
    country: '越南',
    city: '广宁',
    region: '亚洲',
    category: '海岛度假',
    grade: '精品',
    lat: 20.9101,
    lng: 107.1839,
    tagline: '海上喀斯特群岛与邮轮航线营造出层叠水景',
    description: '适合表现海湾群岛分布和度假巡游路线。',
    bestSeason: '10-4 月',
    tags: ['海湾', '邮轮', '海岛'],
    highlights: ['天堂岛', '惊讶洞', '海上邮轮'],
    images: wmCard('ha-long-bay', 'coast'),
    ticketCny: 180,
    stayCny: 260,
    mealCny: 110,
  },
  {
    id: 'marina-bay',
    name: '滨海湾',
    englishName: 'Marina Bay',
    aliases: ['新加坡滨海湾', 'Marina Bay Sands'],
    country: '新加坡',
    city: '新加坡',
    region: '亚洲',
    category: '城市地标',
    grade: '精品',
    lat: 1.2834,
    lng: 103.8607,
    tagline: '未来感天际线与滨水公共空间构成亚洲都市地标',
    description: '适合城市夜景、建筑与公共艺术主题的可视化浏览。',
    bestSeason: '全年',
    tags: ['城市夜景', '建筑', '滨水'],
    highlights: ['金沙酒店', '鱼尾狮', '滨海湾花园'],
    images: wmCard('marina-bay', 'city'),
    ticketCny: 0,
    stayCny: 980,
    mealCny: 260,
  },
  {
    id: 'bali-ubud',
    name: '巴厘岛乌布',
    englishName: 'Ubud Bali',
    aliases: ['巴厘岛', '乌布梯田', 'Bali'],
    country: '印度尼西亚',
    city: '乌布',
    region: '亚洲',
    category: '海岛度假',
    grade: '精品',
    lat: -8.5069,
    lng: 115.2625,
    tagline: '热带梯田、雨林与海岛度假气质在同一区域交汇',
    description: '适合展示海岛慢生活、自然景观与文化村落组合路线。',
    bestSeason: '4-10 月',
    tags: ['海岛', '梯田', '度假'],
    highlights: ['德格拉朗梯田', '乌布皇宫', '丛林秋千'],
    images: wmCard('bali-ubud', 'coast'),
    ticketCny: 60,
    stayCny: 360,
    mealCny: 120,
  },
  {
    id: 'dubai-burj-khalifa',
    name: '哈利法塔',
    englishName: 'Burj Khalifa',
    aliases: ['迪拜塔', '迪拜哈利法塔'],
    country: '阿联酋',
    city: '迪拜',
    region: '亚洲',
    category: '城市地标',
    grade: '精品',
    lat: 25.1972,
    lng: 55.2744,
    tagline: '超高层城市地标与沙漠都市景观形成强烈对比',
    description: '适合做城市地标类节点，突出天际线与观景视角。',
    bestSeason: '11-3 月',
    tags: ['摩天楼', '城市地标', '夜景'],
    highlights: ['At The Top', '迪拜喷泉', '迪拜购物中心'],
    images: wmCard('dubai-burj-khalifa', 'city'),
    ticketCny: 260,
    stayCny: 720,
    mealCny: 250,
  },
  {
    id: 'jeju-island',
    name: '济州岛',
    englishName: 'Jeju Island',
    aliases: ['韩国济州岛', 'Jeju'],
    country: '韩国',
    city: '济州',
    region: '亚洲',
    category: '海岛度假',
    grade: '精品',
    lat: 33.4996,
    lng: 126.5312,
    tagline: '火山岛、海岸公路与度假节奏结合的东北亚热门海岛',
    description: '适合展示海岛公路、火山地貌与轻度假主题。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['海岛', '火山地貌', '度假'],
    highlights: ['城山日出峰', '牛岛', '涉地可支'],
    images: wmCard('jeju-island', 'coast'),
    ticketCny: 80,
    stayCny: 420,
    mealCny: 150,
  },
  {
    id: 'bagan',
    name: '蒲甘',
    englishName: 'Bagan',
    aliases: ['缅甸蒲甘', 'Bagan temples'],
    country: '缅甸',
    city: '蒲甘',
    region: '亚洲',
    category: '人文古迹',
    grade: '精品',
    lat: 21.1717,
    lng: 94.8585,
    tagline: '平原寺塔群与日出热气球共同构建佛塔景观矩阵',
    description: '适合展示遗迹群密集分布与晨昏时段体验。',
    bestSeason: '11-2 月',
    tags: ['佛塔群', '日出', '热气球'],
    highlights: ['阿南达寺', '瑞山陀塔', '日出观景点'],
    images: wmCard('bagan', 'heritage'),
    ticketCny: 120,
    stayCny: 220,
    mealCny: 90,
  },
  {
    id: 'eiffel-tower',
    name: '埃菲尔铁塔',
    englishName: 'Eiffel Tower',
    aliases: ['法国浪漫铁塔', '巴黎铁塔', '艾菲尔铁塔'],
    country: '法国',
    city: '巴黎',
    region: '欧洲',
    category: '城市地标',
    grade: '5A',
    lat: 48.8584,
    lng: 2.2945,
    tagline: '巴黎天际线上的经典铁塔，是浪漫城市的全球符号',
    description: '适合做自然语言搜索示例，也适合搭配城市路线规划。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['浪漫', '城市地标', '夜景'],
    highlights: ['战神广场', '塞纳河游船', '塔顶观景'],
    images: wmCard('eiffel-tower', 'city'),
    ticketCny: 220,
    stayCny: 920,
    mealCny: 320,
  },
  {
    id: 'santorini',
    name: '圣托里尼',
    englishName: 'Santorini',
    aliases: ['希腊圣托里尼', '蓝顶教堂'],
    country: '希腊',
    city: '费拉',
    region: '欧洲',
    category: '海岛度假',
    grade: '精品',
    lat: 36.3932,
    lng: 25.4615,
    tagline: '火山海湾与白墙蓝顶形成高辨识度海岛天际线',
    description: '适合做海岛与日落类主题节点，视觉识别度极高。',
    bestSeason: '5-6 月 / 9 月',
    tags: ['海岛', '日落', '浪漫'],
    highlights: ['伊亚日落', '费拉步道', '火山口游船'],
    images: wmCard('santorini', 'coast'),
    ticketCny: 0,
    stayCny: 860,
    mealCny: 260,
  },
  {
    id: 'colosseum',
    name: '罗马斗兽场',
    englishName: 'Colosseum',
    aliases: ['意大利斗兽场', '罗马竞技场'],
    country: '意大利',
    city: '罗马',
    region: '欧洲',
    category: '人文古迹',
    grade: '5A',
    lat: 41.8902,
    lng: 12.4922,
    tagline: '古罗马巨型剧场与帝国叙事构成欧洲古迹代表',
    description: '适合展示古城遗迹与周边步行游线的空间关系。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['古罗马', '遗迹', '城市古迹'],
    highlights: ['斗兽场', '古罗马广场', '君士坦丁凯旋门'],
    images: wmCard('colosseum', 'heritage'),
    ticketCny: 180,
    stayCny: 780,
    mealCny: 240,
  },
  {
    id: 'sagrada-familia',
    name: '圣家堂',
    englishName: 'Sagrada Familia',
    aliases: ['巴塞罗那圣家堂', '高迪圣家堂'],
    country: '西班牙',
    city: '巴塞罗那',
    region: '欧洲',
    category: '城市地标',
    grade: '精品',
    lat: 41.4036,
    lng: 2.1744,
    tagline: '高迪建筑语言与城市街区肌理形成强烈视觉记忆',
    description: '适合把现代建筑地标与城市漫游动线结合起来呈现。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['建筑', '高迪', '城市漫游'],
    highlights: ['圣家堂', '巴特罗之家', '古埃尔公园'],
    images: wmCard('sagrada-familia', 'city'),
    ticketCny: 230,
    stayCny: 680,
    mealCny: 210,
  },
  {
    id: 'zermatt',
    name: '采尔马特',
    englishName: 'Zermatt',
    aliases: ['马特洪峰', '瑞士雪山小镇'],
    country: '瑞士',
    city: '采尔马特',
    region: '欧洲',
    category: '自然景观',
    grade: '精品',
    lat: 46.0207,
    lng: 7.7491,
    tagline: '雪山、冰川与阿尔卑斯小镇构成高山旅行代表场景',
    description: '适合展示雪山、高海拔观景和轨道交通串联路线。',
    bestSeason: '12-3 月 / 7-9 月',
    tags: ['雪山', '高山', '火车'],
    highlights: ['马特洪峰', '戈尔内格拉特', '冰川天堂'],
    images: wmCard('zermatt', 'nature'),
    ticketCny: 0,
    stayCny: 1280,
    mealCny: 320,
  },
  {
    id: 'reykjavik',
    name: '雷克雅未克',
    englishName: 'Reykjavik',
    aliases: ['冰岛首都', '冰岛极光'],
    country: '冰岛',
    city: '雷克雅未克',
    region: '欧洲',
    category: '自然景观',
    grade: '精品',
    lat: 64.1466,
    lng: -21.9426,
    tagline: '极地光影、火山地貌与城市补给并存的北境中转站',
    description: '可串联极光、冰川、温泉和环岛路线等主题内容。',
    bestSeason: '9-3 月 / 6-8 月',
    tags: ['极光', '火山', '公路旅行'],
    highlights: ['蓝湖温泉', '黄金圈', '哈尔格林姆教堂'],
    images: wmCard('reykjavik', 'nature'),
    ticketCny: 120,
    stayCny: 980,
    mealCny: 300,
  },
  {
    id: 'venice',
    name: '威尼斯',
    englishName: 'Venice',
    aliases: ['水城威尼斯', '威尼斯水城'],
    country: '意大利',
    city: '威尼斯',
    region: '欧洲',
    category: '城市地标',
    grade: '精品',
    lat: 45.4408,
    lng: 12.3155,
    tagline: '水巷与桥梁构成独特城市肌理，是慢游与摄影的经典目的地',
    description: '适合在地球浏览中展示水城结构和重点节点分布。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['水城', '桥梁', '浪漫'],
    highlights: ['圣马可广场', '大运河', '里亚托桥'],
    images: wmCard('venice', 'city'),
    ticketCny: 0,
    stayCny: 860,
    mealCny: 260,
  },
  {
    id: 'neuschwanstein',
    name: '新天鹅堡',
    englishName: 'Neuschwanstein Castle',
    aliases: ['德国新天鹅堡', '天鹅堡'],
    country: '德国',
    city: '菲森',
    region: '欧洲',
    category: '人文古迹',
    grade: '精品',
    lat: 47.5576,
    lng: 10.7498,
    tagline: '山林中的童话城堡与湖泊地形组成高识别度画面',
    description: '适合展示城堡地标与周边山林湖泊景观的复合关系。',
    bestSeason: '5-10 月',
    tags: ['城堡', '童话', '湖山'],
    highlights: ['玛丽安桥', '霍恩施万高', '阿尔卑斯景观'],
    images: wmCard('neuschwanstein', 'heritage'),
    ticketCny: 160,
    stayCny: 620,
    mealCny: 220,
  },
  {
    id: 'plitvice',
    name: '十六湖国家公园',
    englishName: 'Plitvice Lakes',
    aliases: ['克罗地亚十六湖', '十六湖'],
    country: '克罗地亚',
    city: '普利特维采',
    region: '欧洲',
    category: '自然景观',
    grade: '精品',
    lat: 44.88,
    lng: 15.6167,
    tagline: '层叠湖泊与瀑布系统构成蓝绿相间的自然景观',
    description: '适合展示湖泊群与步道型浏览路线。',
    bestSeason: '5-10 月',
    tags: ['瀑布', '湖泊', '国家公园'],
    highlights: ['上湖群', '下湖群', '木栈道'],
    images: wmCard('plitvice', 'nature'),
    ticketCny: 220,
    stayCny: 420,
    mealCny: 150,
  },
  {
    id: 'prague-castle',
    name: '布拉格城堡',
    englishName: 'Prague Castle',
    aliases: ['捷克布拉格城堡', '布拉格古堡'],
    country: '捷克',
    city: '布拉格',
    region: '欧洲',
    category: '人文古迹',
    grade: '精品',
    lat: 50.0909,
    lng: 14.4005,
    tagline: '山丘城堡与红屋顶城市天际线共同构成东欧名片',
    description: '适合与老城步行系统一同展示历史城市的浏览路径。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['城堡', '老城', '欧洲古城'],
    highlights: ['圣维特大教堂', '查理大桥', '黄金巷'],
    images: wmCard('prague-castle', 'heritage'),
    ticketCny: 180,
    stayCny: 480,
    mealCny: 170,
  },
  {
    id: 'amalfi-coast',
    name: '阿马尔菲海岸',
    englishName: 'Amalfi Coast',
    aliases: ['意大利阿马尔菲', '波西塔诺海岸'],
    country: '意大利',
    city: '阿马尔菲',
    region: '欧洲',
    category: '海岛度假',
    grade: '精品',
    lat: 40.6333,
    lng: 14.6029,
    tagline: '悬崖海岸公路与彩色海边聚落构成经典地中海图景',
    description: '适合展示海岸线公路、自驾和海滨聚落的组合体验。',
    bestSeason: '5-6 月 / 9 月',
    tags: ['海岸公路', '地中海', '自驾'],
    highlights: ['波西塔诺', '阿马尔菲小镇', '拉韦洛观景台'],
    images: wmCard('amalfi-coast', 'coast'),
    ticketCny: 0,
    stayCny: 920,
    mealCny: 260,
  },
  {
    id: 'giza',
    name: '吉萨金字塔',
    englishName: 'Pyramids of Giza',
    aliases: ['埃及金字塔', '胡夫金字塔', 'Giza Pyramids'],
    country: '埃及',
    city: '吉萨',
    region: '非洲',
    category: '人文古迹',
    grade: '5A',
    lat: 29.9792,
    lng: 31.1342,
    tagline: '沙漠台地上的金字塔群是文明类搜索的强匹配样本',
    description: '适合自然语言搜索和古文明地标展示。',
    bestSeason: '10-4 月',
    tags: ['古文明', '沙漠', '世界奇迹'],
    highlights: ['胡夫金字塔', '狮身人面像', '日落骑行'],
    images: wmCard('giza', 'heritage'),
    ticketCny: 200,
    stayCny: 320,
    mealCny: 120,
  },
  {
    id: 'serengeti',
    name: '塞伦盖蒂',
    englishName: 'Serengeti',
    aliases: ['坦桑尼亚草原', '塞伦盖蒂草原'],
    country: '坦桑尼亚',
    city: '塞伦盖蒂',
    region: '非洲',
    category: '自然景观',
    grade: '5A',
    lat: -2.3333,
    lng: 34.8333,
    tagline: '东非草原迁徙线路串联出宏观生态叙事',
    description: '适合用点位与迁徙路线表达生态主题。',
    bestSeason: '6-10 月',
    tags: ['野生动物', '草原', '迁徙'],
    highlights: ['角马迁徙', '热气球巡游', '草原日落'],
    images: wmCard('serengeti', 'nature'),
    ticketCny: 560,
    stayCny: 1180,
    mealCny: 260,
  },
  {
    id: 'table-mountain',
    name: '桌山',
    englishName: 'Table Mountain',
    aliases: ['南非桌山', '开普敦桌山'],
    country: '南非',
    city: '开普敦',
    region: '非洲',
    category: '自然景观',
    grade: '精品',
    lat: -33.9628,
    lng: 18.4098,
    tagline: '海湾城市与山体平台形成极具辨识度的景观组合',
    description: '适合展示山海城三种元素叠加的目的地气质。',
    bestSeason: '11-3 月',
    tags: ['山海景观', '缆车', '城市自然'],
    highlights: ['缆车观景', '信号山', '坎普斯湾'],
    images: wmCard('table-mountain', 'nature'),
    ticketCny: 220,
    stayCny: 520,
    mealCny: 180,
  },
  {
    id: 'marrakech',
    name: '马拉喀什老城',
    englishName: 'Marrakech Medina',
    aliases: ['摩洛哥马拉喀什', '红城'],
    country: '摩洛哥',
    city: '马拉喀什',
    region: '非洲',
    category: '城市地标',
    grade: '精品',
    lat: 31.6295,
    lng: -7.9811,
    tagline: '市集巷道与北非建筑色彩营造出强烈的异域氛围',
    description: '适合结合城市市场、街巷和建筑纹理来呈现。',
    bestSeason: '3-5 月 / 9-11 月',
    tags: ['老城', '市集', '北非风格'],
    highlights: ['杰马夫纳广场', '巴伊亚宫', '马若雷勒花园'],
    images: wmCard('marrakech', 'city'),
    ticketCny: 80,
    stayCny: 360,
    mealCny: 130,
  },
  {
    id: 'victoria-falls',
    name: '维多利亚瀑布',
    englishName: 'Victoria Falls',
    aliases: ['赞比亚瀑布', '非洲瀑布'],
    country: '赞比亚',
    city: '利文斯通',
    region: '非洲',
    category: '自然景观',
    grade: '5A',
    lat: -17.9243,
    lng: 25.8572,
    tagline: '跨境巨瀑与峡谷地形形成强烈动势感',
    description: '适合展示跨区域自然景观和瀑布型线路。',
    bestSeason: '2-5 月 / 8-10 月',
    tags: ['瀑布', '峡谷', '冒险'],
    highlights: ['主瀑布观景点', '刀锋桥', '直升机俯瞰'],
    images: wmCard('victoria-falls', 'nature'),
    ticketCny: 260,
    stayCny: 580,
    mealCny: 180,
  },
  {
    id: 'chefchaouen',
    name: '舍夫沙万',
    englishName: 'Chefchaouen',
    aliases: ['摩洛哥蓝城', '蓝色小镇'],
    country: '摩洛哥',
    city: '舍夫沙万',
    region: '非洲',
    category: '城市地标',
    grade: '精品',
    lat: 35.1714,
    lng: -5.2697,
    tagline: '蓝白街巷和山城地形结合出极具辨识度的色彩城市',
    description: '适合做城市色彩标签和街巷漫游型节点。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['蓝色街区', '摄影', '小镇'],
    highlights: ['乌塔哈曼广场', '蓝巷', '山顶清真寺'],
    images: wmCard('chefchaouen', 'city'),
    ticketCny: 0,
    stayCny: 260,
    mealCny: 100,
  },
  {
    id: 'zanzibar',
    name: '桑给巴尔',
    englishName: 'Zanzibar',
    aliases: ['坦桑尼亚海岛', '桑岛'],
    country: '坦桑尼亚',
    city: '石头城',
    region: '非洲',
    category: '海岛度假',
    grade: '精品',
    lat: -6.1659,
    lng: 39.2026,
    tagline: '印度洋海岛与阿拉伯风情老城共同塑造东非海岸体验',
    description: '适合海岛度假与历史港口双重主题展示。',
    bestSeason: '6-10 月 / 12-2 月',
    tags: ['海岛', '老城', '海岸'],
    highlights: ['石头城', '南威海滩', '香料农场'],
    images: wmCard('zanzibar', 'coast'),
    ticketCny: 0,
    stayCny: 420,
    mealCny: 150,
  },
  {
    id: 'grand-canyon',
    name: '大峡谷',
    englishName: 'Grand Canyon',
    aliases: ['美国大峡谷', '科罗拉多大峡谷'],
    country: '美国',
    city: '亚利桑那',
    region: '北美',
    category: '自然景观',
    grade: '5A',
    lat: 36.1069,
    lng: -112.1129,
    tagline: '巨型峡谷地形与日落光影是自然奇观类目的标志性样本',
    description: '适合展示峡谷空间感和公路自驾路线。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['峡谷', '自驾', '日落'],
    highlights: ['南缘', '鹰点', '直升机巡游'],
    images: wmCard('grand-canyon', 'nature'),
    ticketCny: 280,
    stayCny: 520,
    mealCny: 180,
  },
  {
    id: 'banff',
    name: '班夫国家公园',
    englishName: 'Banff National Park',
    aliases: ['班夫', '加拿大班夫'],
    country: '加拿大',
    city: '班夫',
    region: '北美',
    category: '自然景观',
    grade: '5A',
    lat: 51.4968,
    lng: -115.9281,
    tagline: '高山湖泊、冰川谷地与公路风景并存的经典国家公园',
    description: '适合作为户外探索类节点，具备公路旅行和湖泊色彩对比。',
    bestSeason: '6-9 月',
    tags: ['国家公园', '湖泊', '雪山'],
    highlights: ['露易丝湖', '冰原大道', '梦莲湖'],
    images: wmCard('banff', 'nature'),
    ticketCny: 120,
    stayCny: 980,
    mealCny: 240,
  },
  {
    id: 'yellowstone',
    name: '黄石国家公园',
    englishName: 'Yellowstone',
    aliases: ['美国黄石', '黄石公园'],
    country: '美国',
    city: '怀俄明',
    region: '北美',
    category: '自然景观',
    grade: '5A',
    lat: 44.428,
    lng: -110.5885,
    tagline: '地热奇观与野生动物栖息地并置，具有强烈的地学叙事',
    description: '适合展示温泉、间歇泉和国家公园线路。',
    bestSeason: '5-10 月',
    tags: ['间歇泉', '地热', '国家公园'],
    highlights: ['老忠实喷泉', '大棱镜泉', '黄石峡谷'],
    images: wmCard('yellowstone', 'nature'),
    ticketCny: 260,
    stayCny: 760,
    mealCny: 220,
  },
  {
    id: 'statue-of-liberty',
    name: '自由女神像',
    englishName: 'Statue of Liberty',
    aliases: ['纽约自由女神', '纽约女神像'],
    country: '美国',
    city: '纽约',
    region: '北美',
    category: '城市地标',
    grade: '精品',
    lat: 40.6892,
    lng: -74.0445,
    tagline: '纽约港入口的城市象征，兼具历史与天际线联想',
    description: '适合串联纽约城市节点与海港视角。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['纽约', '城市地标', '港口'],
    highlights: ['自由岛', '曼哈顿天际线', '渡轮航线'],
    images: wmCard('statue-of-liberty', 'city'),
    ticketCny: 210,
    stayCny: 1380,
    mealCny: 360,
  },
  {
    id: 'niagara-falls',
    name: '尼亚加拉瀑布',
    englishName: 'Niagara Falls',
    aliases: ['尼亚加拉大瀑布', '加拿大瀑布'],
    country: '加拿大',
    city: '尼亚加拉',
    region: '北美',
    category: '自然景观',
    grade: '精品',
    lat: 43.0962,
    lng: -79.0377,
    tagline: '巨量水势与夜间灯光形成城市近郊型自然奇观',
    description: '适合展示瀑布声势与两岸联动旅游线路。',
    bestSeason: '5-10 月',
    tags: ['瀑布', '游船', '夜景'],
    highlights: ['雾中少女号', '瀑布夜景', 'Skylon Tower'],
    images: wmCard('niagara-falls', 'nature'),
    ticketCny: 180,
    stayCny: 620,
    mealCny: 180,
  },
  {
    id: 'chichen-itza',
    name: '奇琴伊察',
    englishName: 'Chichen Itza',
    aliases: ['墨西哥金字塔', '玛雅金字塔'],
    country: '墨西哥',
    city: '尤卡坦',
    region: '北美',
    category: '人文古迹',
    grade: '5A',
    lat: 20.6843,
    lng: -88.5678,
    tagline: '玛雅文明遗址与热带植被环境共同构成中美洲经典景观',
    description: '适合展示文明遗址与丛林地理环境的结合。',
    bestSeason: '11-4 月',
    tags: ['玛雅文明', '金字塔', '热带古迹'],
    highlights: ['库库尔坎金字塔', '武士神庙', '天文台'],
    images: wmCard('chichen-itza', 'heritage'),
    ticketCny: 240,
    stayCny: 320,
    mealCny: 120,
  },
  {
    id: 'antelope-canyon',
    name: '羚羊峡谷',
    englishName: 'Antelope Canyon',
    aliases: ['美国羚羊谷', '光束峡谷'],
    country: '美国',
    city: '亚利桑那',
    region: '北美',
    category: '自然景观',
    grade: '精品',
    lat: 36.8619,
    lng: -111.3743,
    tagline: '狭缝峡谷与光束效果构成极具戏剧性的摄影空间',
    description: '适合展示地貌细节与时段型观景体验。',
    bestSeason: '3-10 月',
    tags: ['峡谷', '摄影', '光束'],
    highlights: ['上羚羊谷', '下羚羊谷', '鲍威尔湖'],
    images: wmCard('antelope-canyon', 'nature'),
    ticketCny: 520,
    stayCny: 420,
    mealCny: 160,
  },
  {
    id: 'moraine-lake',
    name: '梦莲湖',
    englishName: 'Moraine Lake',
    aliases: ['加拿大梦莲湖', 'Moraine'],
    country: '加拿大',
    city: '班夫',
    region: '北美',
    category: '自然景观',
    grade: '精品',
    lat: 51.3217,
    lng: -116.186,
    tagline: '冰川湖蓝色与十峰山脉共同塑造明信片级湖山画面',
    description: '适合展示湖泊类景点的色彩辨识度与晨昏时段差异。',
    bestSeason: '6-9 月',
    tags: ['冰川湖', '雪山', '晨景'],
    highlights: ['岩石堆观景点', '独木舟', '十峰山脉'],
    images: wmCard('moraine-lake', 'nature'),
    ticketCny: 0,
    stayCny: 920,
    mealCny: 220,
  },
  {
    id: 'machu-picchu',
    name: '马丘比丘',
    englishName: 'Machu Picchu',
    aliases: ['秘鲁马丘比丘', '印加古城'],
    country: '秘鲁',
    city: '库斯科',
    region: '南美',
    category: '人文古迹',
    grade: '5A',
    lat: -13.1631,
    lng: -72.545,
    tagline: '云雾山脊上的印加遗址拥有极强的文明与自然叠加感',
    description: '适合文明遗址与山地铁路路线结合展示。',
    bestSeason: '5-9 月',
    tags: ['印加文明', '山地古迹', '云海'],
    highlights: ['守卫者小屋', '太阳门', '印加古道'],
    images: wmCard('machu-picchu', 'heritage'),
    ticketCny: 380,
    stayCny: 480,
    mealCny: 160,
  },
  {
    id: 'iguazu',
    name: '伊瓜苏瀑布',
    englishName: 'Iguazu Falls',
    aliases: ['伊瓜苏大瀑布', '巴西瀑布', '阿根廷瀑布'],
    country: '阿根廷',
    city: '伊瓜苏港',
    region: '南美',
    category: '自然景观',
    grade: '5A',
    lat: -25.6953,
    lng: -54.4367,
    tagline: '跨境瀑布群与热带雨林形成宏大的自然系统视角',
    description: '适合展示多段瀑布群与雨林线路。',
    bestSeason: '4-9 月',
    tags: ['瀑布群', '雨林', '跨境'],
    highlights: ['魔鬼咽喉', '观景步道', '直升机俯瞰'],
    images: wmCard('iguazu', 'nature'),
    ticketCny: 260,
    stayCny: 360,
    mealCny: 140,
  },
  {
    id: 'christ-redeemer',
    name: '救世基督像',
    englishName: 'Christ the Redeemer',
    aliases: ['里约基督像', '巴西基督像'],
    country: '巴西',
    city: '里约热内卢',
    region: '南美',
    category: '城市地标',
    grade: '精品',
    lat: -22.9519,
    lng: -43.2105,
    tagline: '山顶巨像与海湾城市天际线共同构成里约的视觉符号',
    description: '适合做城市观景台与海湾空间关系展示。',
    bestSeason: '5-10 月',
    tags: ['山顶地标', '城市观景', '海湾'],
    highlights: ['科尔科瓦多山', '糖面包山', '科帕卡巴纳'],
    images: wmCard('christ-redeemer', 'city'),
    ticketCny: 180,
    stayCny: 520,
    mealCny: 160,
  },
  {
    id: 'salar-de-uyuni',
    name: '乌尤尼盐湖',
    englishName: 'Salar de Uyuni',
    aliases: ['玻利维亚盐湖', '天空之镜'],
    country: '玻利维亚',
    city: '乌尤尼',
    region: '南美',
    category: '自然景观',
    grade: '精品',
    lat: -20.1338,
    lng: -67.4891,
    tagline: '干季几何纹理与雨季镜面倒影形成两种极端视觉体验',
    description: '适合展示季节切换造成的强烈视觉反差。',
    bestSeason: '12-3 月 / 6-8 月',
    tags: ['盐湖', '天空之镜', '极简地貌'],
    highlights: ['镜面倒影', '仙人掌岛', '星空摄影'],
    images: wmCard('salar-de-uyuni', 'nature'),
    ticketCny: 0,
    stayCny: 260,
    mealCny: 120,
  },
  {
    id: 'torres-del-paine',
    name: '百内国家公园',
    englishName: 'Torres del Paine',
    aliases: ['智利百内', '巴塔哥尼亚百内'],
    country: '智利',
    city: '巴塔哥尼亚',
    region: '南美',
    category: '自然景观',
    grade: '5A',
    lat: -50.9423,
    lng: -73.4068,
    tagline: '巴塔哥尼亚山峰、冰川与湖泊构成壮阔荒野景观',
    description: '适合表现远距离徒步、湖山和冰川多层次景观。',
    bestSeason: '11-3 月',
    tags: ['徒步', '冰川', '巴塔哥尼亚'],
    highlights: ['W Trek', '百内塔峰', '格雷冰川'],
    images: wmCard('torres-del-paine', 'nature'),
    ticketCny: 260,
    stayCny: 780,
    mealCny: 200,
  },
  {
    id: 'galapagos',
    name: '加拉帕戈斯群岛',
    englishName: 'Galapagos Islands',
    aliases: ['厄瓜多尔加拉帕戈斯', '加拉帕戈斯'],
    country: '厄瓜多尔',
    city: '圣克里斯托瓦尔',
    region: '南美',
    category: '海岛度假',
    grade: '精品',
    lat: -0.9538,
    lng: -90.9656,
    tagline: '火山海岛与特有物种生态构成独特的自然教育场景',
    description: '适合生态主题与群岛分布展示。',
    bestSeason: '12-5 月 / 6-11 月',
    tags: ['群岛', '生态', '火山海岛'],
    highlights: ['海狮海滩', '达尔文研究站', '巡航线路'],
    images: wmCard('galapagos', 'coast'),
    ticketCny: 800,
    stayCny: 720,
    mealCny: 220,
  },
  {
    id: 'easter-island',
    name: '复活节岛',
    englishName: 'Easter Island',
    aliases: ['摩艾石像', '复活节岛石像'],
    country: '智利',
    city: '复活节岛',
    region: '南美',
    category: '人文古迹',
    grade: '精品',
    lat: -27.1127,
    lng: -109.3497,
    tagline: '海岛上的巨型石像群为远洋文明叙事提供了独特入口',
    description: '适合展示海岛文明遗迹与远洋孤岛地理特征。',
    bestSeason: '10-4 月',
    tags: ['石像', '海岛文明', '远洋'],
    highlights: ['阿胡通加里基', '拉诺拉拉库', '阿纳凯纳海滩'],
    images: wmCard('easter-island', 'heritage'),
    ticketCny: 420,
    stayCny: 680,
    mealCny: 220,
  },
  {
    id: 'cusco',
    name: '库斯科',
    englishName: 'Cusco',
    aliases: ['秘鲁库斯科', '印加古城'],
    country: '秘鲁',
    city: '库斯科',
    region: '南美',
    category: '人文古迹',
    grade: '精品',
    lat: -13.5319,
    lng: -71.9675,
    tagline: '高原古城与安第斯文明遗迹串联出的历史入口',
    description: '兼具历史、人文与山地地形叙事，可延展到马丘比丘线路。',
    bestSeason: '5-9 月',
    tags: ['高原古城', '历史', '安第斯'],
    highlights: ['萨克塞华曼', '太阳神殿', '圣谷线路'],
    images: wmCard('cusco', 'heritage'),
    ticketCny: 120,
    stayCny: 320,
    mealCny: 130,
  },
  {
    id: 'sydney-opera-house',
    name: '悉尼歌剧院',
    englishName: 'Sydney Opera House',
    aliases: ['澳大利亚歌剧院', '悉尼歌剧院'],
    country: '澳大利亚',
    city: '悉尼',
    region: '大洋洲',
    category: '城市地标',
    grade: '5A',
    lat: -33.8568,
    lng: 151.2153,
    tagline: '贝壳状建筑与海港大桥共同构成澳洲城市地标',
    description: '适合展示海港城市天际线与文化建筑节点。',
    bestSeason: '9-11 月 / 3-5 月',
    tags: ['建筑', '海港', '城市地标'],
    highlights: ['悉尼港', '海港大桥', '岩石区'],
    images: wmCard('sydney-opera-house', 'city'),
    ticketCny: 260,
    stayCny: 980,
    mealCny: 260,
  },
  {
    id: 'queenstown',
    name: '皇后镇',
    englishName: 'Queenstown',
    aliases: ['新西兰皇后镇', '极限运动小镇'],
    country: '新西兰',
    city: '皇后镇',
    region: '大洋洲',
    category: '自然景观',
    grade: '精品',
    lat: -45.0312,
    lng: 168.6626,
    tagline: '湖山城市与极限运动场景叠加的南半球旅行名片',
    description: '适合表达 adventure 主题，在单个节点中整合湖景、雪山与极限活动。',
    bestSeason: '12-2 月 / 6-8 月',
    tags: ['户外冒险', '湖山', '四季玩法'],
    highlights: ['瓦卡蒂普湖', '天空缆车', '格林诺奇公路'],
    images: wmCard('queenstown', 'nature'),
    ticketCny: 0,
    stayCny: 860,
    mealCny: 240,
  },
  {
    id: 'great-barrier-reef',
    name: '大堡礁',
    englishName: 'Great Barrier Reef',
    aliases: ['澳大利亚大堡礁', '珊瑚海'],
    country: '澳大利亚',
    city: '凯恩斯',
    region: '大洋洲',
    category: '海岛度假',
    grade: '5A',
    lat: -18.2871,
    lng: 147.6992,
    tagline: '全球知名珊瑚礁系统适合海洋生态与海岛航线浏览',
    description: '适合把海洋生态、潜水体验和群岛线路结合起来展示。',
    bestSeason: '6-10 月',
    tags: ['珊瑚礁', '潜水', '海洋生态'],
    highlights: ['外堡礁潜点', '直升机俯瞰', '白天堂海滩'],
    images: wmCard('great-barrier-reef', 'coast'),
    ticketCny: 860,
    stayCny: 760,
    mealCny: 220,
  },
  {
    id: 'uluru',
    name: '乌鲁鲁',
    englishName: 'Uluru',
    aliases: ['艾尔斯岩', '澳洲红石'],
    country: '澳大利亚',
    city: '北领地',
    region: '大洋洲',
    category: '自然景观',
    grade: '精品',
    lat: -25.3444,
    lng: 131.0369,
    tagline: '红色巨岩与沙漠平原构成澳洲内陆最经典的地貌符号',
    description: '适合展示单体地貌景观与日出日落光影变化。',
    bestSeason: '5-9 月',
    tags: ['沙漠', '巨岩', '日落'],
    highlights: ['日落观景区', '卡塔丘塔', '原住民文化中心'],
    images: wmCard('uluru', 'nature'),
    ticketCny: 180,
    stayCny: 680,
    mealCny: 210,
  },
  {
    id: 'milford-sound',
    name: '米尔福德峡湾',
    englishName: 'Milford Sound',
    aliases: ['新西兰峡湾', '米佛峡湾'],
    country: '新西兰',
    city: '峡湾国家公园',
    region: '大洋洲',
    category: '自然景观',
    grade: '5A',
    lat: -44.6718,
    lng: 167.9256,
    tagline: '峡湾峭壁、瀑布与雨林共同塑造冷峻而壮阔的南岛景观',
    description: '适合展示峡湾航线与山海垂直地形关系。',
    bestSeason: '11-4 月',
    tags: ['峡湾', '邮轮', '瀑布'],
    highlights: ['米特峰', '峡湾游船', '镜湖公路'],
    images: wmCard('milford-sound', 'nature'),
    ticketCny: 420,
    stayCny: 520,
    mealCny: 180,
  },
  {
    id: 'hobbiton',
    name: '霍比屯',
    englishName: 'Hobbiton',
    aliases: ['指环王村庄', '霍比特村'],
    country: '新西兰',
    city: '玛塔玛塔',
    region: '大洋洲',
    category: '城市地标',
    grade: '精品',
    lat: -37.8721,
    lng: 175.6821,
    tagline: '电影场景与草坡地貌结合，具有鲜明的内容 IP 识别度',
    description: '适合把影视主题与自然乡村景观结合展示。',
    bestSeason: '全年',
    tags: ['电影场景', 'IP 景点', '乡村'],
    highlights: ['袋底洞', '绿龙酒馆', '拍摄场景导览'],
    images: wmCard('hobbiton', 'city'),
    ticketCny: 520,
    stayCny: 420,
    mealCny: 160,
  },
  {
    id: 'golden-gate-bridge',
    name: '金门大桥',
    englishName: 'Golden Gate Bridge',
    aliases: ['旧金山金门大桥', 'Golden Gate', '三藩市大桥'],
    country: '美国',
    city: '旧金山',
    region: '北美',
    category: '城市地标',
    grade: '精品',
    lat: 37.8199,
    lng: -122.4783,
    tagline: '橙红色悬索桥跨越海峡雾带，是西海岸最具辨识度的城市自然交界',
    description:
      '1937 年通车的国际土木工程地标，常出现在晨雾与夕阳画面中；可结合要塞公园、马林海角步道理解海湾地形与桥梁结构。',
    bestSeason: '9-11 月 / 4-5 月',
    tags: ['海湾', '桥梁', '摄影'],
    highlights: ['Battery Spencer 观景点', '步行/自行车过桥', '恶魔岛远眺'],
    images: wmCard('golden-gate-bridge', 'city'),
    ticketCny: 0,
    stayCny: 1120,
    mealCny: 280,
  },
  {
    id: 'cloud-gate-chicago',
    name: '云门（千禧公园）',
    englishName: 'Cloud Gate',
    aliases: ['芝加哥豆子', 'The Bean', '千禧公园'],
    country: '美国',
    city: '芝加哥',
    region: '北美',
    category: '城市地标',
    grade: '精品',
    lat: 41.8826,
    lng: -87.6233,
    tagline: '镜面不锈钢雕塑映射天际线，是当代公共艺术与滨湖城市空间的代表',
    description:
      '安尼施·卡普尔设计的巨型「豆子」雕塑，表面反射千禧公园与密歇根大道建筑群；适合作为城市艺术节点与冬季冰场季节对比浏览。',
    bestSeason: '5-10 月',
    tags: ['公共艺术', '镜面', '滨湖'],
    highlights: ['雕塑底部仰拍', '杰·普利兹克露天音乐厅', '湖滨步道'],
    images: wmCard('cloud-gate-chicago', 'city'),
    ticketCny: 0,
    stayCny: 920,
    mealCny: 240,
  },
  {
    id: 'las-vegas-strip',
    name: '拉斯维加斯大道',
    englishName: 'Las Vegas Strip',
    aliases: ['赌城大道', 'Strip', '拉斯维加斯夜景'],
    country: '美国',
    city: '拉斯维加斯',
    region: '北美',
    category: '城市地标',
    grade: '精品',
    lat: 36.1147,
    lng: -115.1728,
    tagline: '霓虹主题酒店与巨型秀场合奏出沙漠中的不夜城景观',
    description:
      '长约 6.8 公里的度假区走廊，集中了金字塔、威尼斯运河、摩天轮等地标建筑；适合夜景、娱乐产业与城市能耗话题的可视化对照。',
    bestSeason: '3-5 月 / 10-11 月',
    tags: ['夜景', '娱乐', '沙漠城市'],
    highlights: ['百乐宫喷泉', '豪客摩天轮', '主题酒店建筑群'],
    images: wmCard('las-vegas-strip', 'city'),
    ticketCny: 0,
    stayCny: 880,
    mealCny: 260,
  },
  {
    id: 'washington-national-mall',
    name: '华盛顿国家广场',
    englishName: 'National Mall',
    aliases: ['华盛顿纪念碑', '国会山', '林肯纪念堂'],
    country: '美国',
    city: '华盛顿',
    region: '北美',
    category: '城市地标',
    grade: '精品',
    lat: 38.8895,
    lng: -77.0353,
    tagline: '纪念性建筑与中轴线草坪构成美国首都的政治文化空间',
    description:
      '从林肯纪念堂到国会大厦的开放轴线串联越战、韩战、二战等纪念园；适合理解纪念性景观序列与公共集会传统。',
    bestSeason: '4-6 月 / 9-11 月',
    tags: ['纪念建筑', '中轴线', '博物馆群'],
    highlights: ['林肯纪念堂倒影池', '华盛顿纪念碑', '史密森博物馆'],
    images: wmCard('washington-national-mall', 'city'),
    ticketCny: 0,
    stayCny: 1020,
    mealCny: 220,
  },
  {
    id: 'tokyo-shibuya-scramble',
    name: '涩谷十字路口',
    englishName: 'Shibuya Scramble Crossing',
    aliases: ['涩谷站前', '东京十字路口', 'Shibuya Crossing'],
    country: '日本',
    city: '东京',
    region: '亚洲',
    category: '城市地标',
    grade: '精品',
    lat: 35.6595,
    lng: 139.7004,
    tagline: '超高密度人流与巨型屏幕共同定义当代都市节奏',
    description:
      '与涩谷车站相连的行人全向过街节点，高峰时单次可通行上千人；可结合忠犬八公像、涩谷 Sky 展望台理解立体交通与商业垂直堆叠。',
    bestSeason: '全年',
    tags: ['人潮', '霓虹', '轨道交通'],
    highlights: ['二层连廊俯拍', '涩谷 Sky', '宫下公园'],
    images: wmCard('tokyo-shibuya-scramble', 'city'),
    ticketCny: 120,
    stayCny: 720,
    mealCny: 200,
  },
  {
    id: 'nara-todaiji',
    name: '东大寺（奈良）',
    englishName: 'Tōdai-ji',
    aliases: ['奈良大佛', '东大寺大佛殿', 'Nara Daibutsu'],
    country: '日本',
    city: '奈良',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 34.6889,
    lng: 135.8398,
    tagline: '木构大佛殿与放养的鹿群构成古都宗教与自然共存的画面',
    description:
      '752 年开光的华严宗大本山，大佛殿曾为世界最大木构建筑之一；寺内卢舍那佛铜像与奈良公园鹿群形成强烈文化记忆点。',
    bestSeason: '3-5 月 / 10-11 月',
    tags: ['木构建筑', '佛教艺术', '奈良鹿'],
    highlights: ['大佛殿', '二月堂俯瞰', '若草山'],
    images: wmCard('nara-todaiji', 'heritage'),
    ticketCny: 60,
    stayCny: 480,
    mealCny: 160,
  },
  {
    id: 'zhangjiajie-avatar',
    name: '张家界国家森林公园',
    englishName: 'Zhangjiajie National Forest Park',
    aliases: ['阿凡达哈利路亚山', '武陵源', '张家界石柱'],
    country: '中国',
    city: '张家界',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 29.3257,
    lng: 110.4322,
    tagline: '石英砂岩峰林与云雾共同塑造垂直石林奇观',
    description:
      '世界自然遗产武陵源核心景区，数千座石峰柱林立；百龙天梯、玻璃栈道与黄石寨环线适合展示喀斯特型峰林地貌与旅游基础设施。',
    bestSeason: '4-6 月 / 9-11 月',
    tags: ['峰林', '世界遗产', '玻璃栈道'],
    highlights: ['袁家界', '天子山', '金鞭溪'],
    images: wmCard('zhangjiajie-avatar', 'nature'),
    ticketCny: 228,
    stayCny: 320,
    mealCny: 120,
  },
  {
    id: 'huangshan-yellow-mountain',
    name: '黄山',
    englishName: 'Mount Huangshan',
    aliases: ['黄山风景区', '徽州黄山', 'Yellow Mountain'],
    country: '中国',
    city: '黄山',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 30.1333,
    lng: 118.1667,
    tagline: '奇松、怪石、云海、温泉四绝定义中国山水审美高峰',
    description:
      '世界文化与自然双遗产，花岗岩峰林与黄山松共生；冬雪云海与夏季避暑形成强烈季节对比，适合山地气候与步道系统展示。',
    bestSeason: '四季皆宜（冬雪云海 / 春秋摄影）',
    tags: ['山岳', '云海', '世界遗产'],
    highlights: ['光明顶', '迎客松', '西海大峡谷'],
    images: wmCard('huangshan-yellow-mountain', 'nature'),
    ticketCny: 190,
    stayCny: 480,
    mealCny: 140,
  },
  {
    id: 'guilin-li-river',
    name: '漓江山水',
    englishName: 'Li River',
    aliases: ['桂林漓江', '阳朔山水', '人民币背景'],
    country: '中国',
    city: '桂林',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 24.92,
    lng: 110.45,
    tagline: '喀斯特峰丛倒映江面，是中国画式风景的现实范本',
    description:
      '从桂林至阳朔的喀斯特峰林河谷走廊，竹筏与游船串联兴坪、九马画山等节点；适合展示河曲地貌与河岸聚落关系。',
    bestSeason: '4-10 月',
    tags: ['喀斯特', '江河', '竹筏'],
    highlights: ['兴坪佳境', '遇龙河', '阳朔西街'],
    images: wmCard('guilin-li-river', 'nature'),
    ticketCny: 210,
    stayCny: 360,
    mealCny: 110,
  },
  {
    id: 'hoi-an-ancient-town',
    name: '会安古城',
    englishName: 'Hoi An Ancient Town',
    aliases: ['越南会安', '灯笼古城', 'Hoi An'],
    country: '越南',
    city: '会安',
    region: '亚洲',
    category: '人文古迹',
    grade: '精品',
    lat: 15.8801,
    lng: 108.338,
    tagline: '东南亚贸易港遗存与灯笼夜市交织的滨水古城',
    description:
      '15-19 世纪中日欧风格融合的港口聚落，世界遗产；黄墙木构、会安廊桥与秋盆河船灯适合展示历史港市肌理与节庆灯光。',
    bestSeason: '2-4 月',
    tags: ['世界遗产', '夜市', '混血建筑'],
    highlights: ['日本廊桥', '福建会馆', '灯笼街'],
    images: wmCard('hoi-an-ancient-town', 'heritage'),
    ticketCny: 80,
    stayCny: 280,
    mealCny: 90,
  },
  {
    id: 'cinque-terre',
    name: '五渔村',
    englishName: 'Cinque Terre',
    aliases: ['意大利五渔村', '马纳罗拉', 'Monterosso'],
    country: '意大利',
    city: '拉斯佩齐亚省',
    region: '欧洲',
    category: '海岛度假',
    grade: '精品',
    lat: 44.1284,
    lng: 9.7129,
    tagline: '利古里亚海崖上的彩色渔村与葡萄梯田构成地中海经典画面',
    description:
      '蒙泰罗索、韦尔纳扎等五座渔村由步道与区域火车串联，世界遗产；适合海岸线聚落、徒步径与海洋侵蚀地貌的综合浏览。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['海岸村落', '徒步', '世界遗产'],
    highlights: ['马纳罗拉日落', '爱之路', '韦尔纳扎港'],
    images: wmCard('cinque-terre', 'coast'),
    ticketCny: 0,
    stayCny: 860,
    mealCny: 220,
  },
  {
    id: 'meteora-monasteries',
    name: '迈泰奥拉修道院群',
    englishName: 'Meteora',
    aliases: ['希腊天空之城', '梅黛奥拉', 'Meteora Greece'],
    country: '希腊',
    city: '卡兰巴卡',
    region: '欧洲',
    category: '人文古迹',
    grade: '5A',
    lat: 39.7217,
    lng: 21.6306,
    tagline: '砂岩柱顶的中世纪修道院呈现信仰与险峻地形的极端结合',
    description:
      '东正教修道院群建于塞萨利平原突起的巨岩顶端，世界遗产；可结合登山径、缆车与日落光线理解宗教建筑如何嵌入垂直地貌。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['世界遗产', '宗教建筑', '攀岩地貌'],
    highlights: ['大迈泰奥拉修道院', '瓦尔拉姆修道院', '日落观景点'],
    images: wmCard('meteora-monasteries', 'heritage'),
    ticketCny: 120,
    stayCny: 520,
    mealCny: 160,
  },
  {
    id: 'lake-bled',
    name: '布莱德湖',
    englishName: 'Lake Bled',
    aliases: ['斯洛文尼亚布莱德', '湖心岛教堂', 'Bled'],
    country: '斯洛文尼亚',
    city: '布莱德',
    region: '欧洲',
    category: '自然景观',
    grade: '精品',
    lat: 46.3667,
    lng: 14.1,
    tagline: '阿尔卑斯前山湖泊、城堡与湖心岛教堂构成童话式湖山构图',
    description:
      '冰川湖与布莱德城堡俯瞰湖心圣母升天教堂，传统 pletna 木船摆渡；冬季雪景与夏季划船形成高反差度假体验。',
    bestSeason: '5-9 月 / 冬季雪景',
    tags: ['冰川湖', '教堂', '徒步'],
    highlights: ['城堡观景台', '湖心岛', '文特加峡谷'],
    images: wmCard('lake-bled', 'nature'),
    ticketCny: 180,
    stayCny: 680,
    mealCny: 180,
  },
  {
    id: 'budapest-parliament',
    name: '匈牙利国会大厦',
    englishName: 'Hungarian Parliament Building',
    aliases: ['布达佩斯国会', '多瑙河畔国会', 'Országház'],
    country: '匈牙利',
    city: '布达佩斯',
    region: '欧洲',
    category: '城市地标',
    grade: '精品',
    lat: 47.5079,
    lng: 19.0453,
    tagline: '新哥特式穹顶与多瑙河倒影构成中欧河畔天际线焦点',
    description:
      '1904 年落成的新哥特复兴风格立法建筑，内部皇冠厅与楼梯间装饰华丽；夜间灯光与对岸布达城堡形成经典双城景观轴。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['新哥特', '河畔', '夜景'],
    highlights: ['多瑙河游船视角', '内部导览', '科苏特广场'],
    images: wmCard('budapest-parliament', 'city'),
    ticketCny: 160,
    stayCny: 560,
    mealCny: 170,
  },
  {
    id: 'dubrovnik-old-town',
    name: '杜布罗夫尼克老城',
    englishName: 'Dubrovnik Old Town',
    aliases: ['君临城', '克罗地亚杜城', 'Dubrovnik'],
    country: '克罗地亚',
    city: '杜布罗夫尼克',
    region: '欧洲',
    category: '人文古迹',
    grade: '精品',
    lat: 42.6507,
    lng: 18.0944,
    tagline: '亚得里亚海石砌老城与城墙步道展现中世纪港城防御美学',
    description:
      '世界遗产拉古萨共和国核心，石灰岩建筑与城墙绕城；权游取景地带动文化 IP 联想，可结合洛克鲁姆岛与缆车山顶俯瞰。',
    bestSeason: '5-6 月 / 9 月',
    tags: ['城墙', '世界遗产', '亚得里亚海'],
    highlights: ['城墙漫步', '斯特拉顿大街', '明阙塔'],
    images: wmCard('dubrovnik-old-town', 'heritage'),
    ticketCny: 260,
    stayCny: 720,
    mealCny: 200,
  },
  {
    id: 'mont-saint-michel',
    name: '圣米歇尔山',
    englishName: 'Mont Saint-Michel',
    aliases: ['法国圣米歇尔', '诺曼底圣山', 'Mont-Saint-Michel'],
    country: '法国',
    city: '诺曼底',
    region: '欧洲',
    category: '人文古迹',
    grade: '5A',
    lat: 48.636,
    lng: -1.5115,
    tagline: '潮汐岛与哥特式修道院构成欧洲最具戏剧性的海陆交界地标',
    description:
      '涨潮时岛屿与滩涂分离，中世纪本笃会修道院踞顶而下；潮差可达十余米，适合潮汐节律、朝圣史与海岸生态的跨学科展示。',
    bestSeason: '4-10 月',
    tags: ['潮汐岛', '修道院', '世界遗产'],
    highlights: ['修道院回廊', '滩涂徒步', '夜景灯光'],
    images: wmCard('mont-saint-michel', 'heritage'),
    ticketCny: 120,
    stayCny: 780,
    mealCny: 200,
  },
  {
    id: 'amsterdam-canal-ring',
    name: '阿姆斯特丹运河带',
    englishName: 'Amsterdam Canal Ring',
    aliases: ['荷兰运河', '17 世纪运河带', 'Grachtengordel'],
    country: '荷兰',
    city: '阿姆斯特丹',
    region: '欧洲',
    category: '城市地标',
    grade: '精品',
    lat: 52.3676,
    lng: 4.9041,
    tagline: '同心半环形运河与山墙房屋定义低地城市的水网肌理',
    description:
      '世界遗产城市工程，运河、船屋与自行车道交织；国立博物馆、安妮之家与九街街区适合串联艺术与市民生活主题。',
    bestSeason: '4-9 月',
    tags: ['运河', '自行车城', '博物馆'],
    highlights: ['王子运河游船', '博物馆广场', '红灯区建筑史导览'],
    images: wmCard('amsterdam-canal-ring', 'city'),
    ticketCny: 180,
    stayCny: 820,
    mealCny: 220,
  },
  {
    id: 'iceland-blue-lagoon',
    name: '蓝湖温泉',
    englishName: 'Blue Lagoon',
    aliases: ['冰岛蓝湖', 'Blue Lagoon Iceland'],
    country: '冰岛',
    city: '格林达维克',
    region: '欧洲',
    category: '自然景观',
    grade: '精品',
    lat: 63.8804,
    lng: -22.4495,
    tagline: '地热海水与硅泥面膜塑造冰岛最具代表性的康养景观',
    description:
      '利用斯瓦森吉地热电厂排水形成的露天温泉湖，乳蓝色水体与黑色熔岩台地对比强烈；可延伸至雷克雅内斯半岛火山带与极光季节组合。',
    bestSeason: '全年',
    tags: ['温泉', '地热', '康养'],
    highlights: ['硅泥面膜', '水中吧台', '熔岩步道'],
    images: wmCard('iceland-blue-lagoon', 'nature'),
    ticketCny: 520,
    stayCny: 1120,
    mealCny: 260,
  },
  {
    id: 'perito-moreno-glacier',
    name: '佩里托莫雷诺冰川',
    englishName: 'Perito Moreno Glacier',
    aliases: ['阿根廷冰川', '莫雷诺冰川', 'Los Glaciares'],
    country: '阿根廷',
    city: '埃尔卡拉法特',
    region: '南美',
    category: '自然景观',
    grade: '5A',
    lat: -50.4797,
    lng: -73.2451,
    tagline: '活冰川伸入阿根廷湖，崩裂场面具有极强动态视觉冲击',
    description:
      '巴塔哥尼亚冰原东缘的低海拔冰川，常发生冰舌崩解；栈道系统近距离观察冰裂隙与绿松石色冰墙，适合冰川退缩与淡水储量议题讨论。',
    bestSeason: '11-3 月',
    tags: ['冰川', '国家公园', '徒步栈道'],
    highlights: ['栈道观冰墙', '迷你徒步', '阿根廷湖游船'],
    images: wmCard('perito-moreno-glacier', 'nature'),
    ticketCny: 200,
    stayCny: 680,
    mealCny: 160,
  },
  {
    id: 'atacama-desert',
    name: '阿塔卡马沙漠',
    englishName: 'Atacama Desert',
    aliases: ['智利阿塔卡马', '圣佩德罗', '世界旱极'],
    country: '智利',
    city: '圣佩德罗德阿塔卡马',
    region: '南美',
    category: '自然景观',
    grade: '精品',
    lat: -22.908,
    lng: -68.1997,
    tagline: '极端干旱高地与盐湖、间歇泉构成类火星地表实验室',
    description:
      '年均降水极低，阿塔卡马盐沼、月亮谷与塔提奥间歇泉提供独特地貌；高海拔与无光污染亦使其成为世界顶级天文台集群所在地。',
    bestSeason: '全年（雨季少量降水多在 1-3 月）',
    tags: ['盐湖', '星空', '间歇泉'],
    highlights: ['月亮谷日落', '阿塔卡马盐沼', 'ALMA 射电望远镜外围'],
    images: wmCard('atacama-desert', 'nature'),
    ticketCny: 120,
    stayCny: 620,
    mealCny: 140,
  },
  {
    id: 'cartagena-old-town',
    name: '卡塔赫纳老城',
    englishName: 'Cartagena Old Town',
    aliases: ['哥伦比亚卡塔赫纳', '加勒比殖民城', 'Cartagena de Indias'],
    country: '哥伦比亚',
    city: '卡塔赫纳',
    region: '南美',
    category: '人文古迹',
    grade: '精品',
    lat: 10.4231,
    lng: -75.5483,
    tagline: '加勒比海岸殖民要塞与色彩街巷构成拉美历史港口范本',
    description:
      '16-17 世纪西班牙殖民防御体系世界遗产，城墙、钟楼与阳台花卉密集；可结合奴隶史、海盗史与当代文学（马尔克斯）文化线路。',
    bestSeason: '12-4 月',
    tags: ['殖民建筑', '加勒比', '要塞'],
    highlights: ['城墙日落', '圣费利佩城堡', '圣多明各广场'],
    images: wmCard('cartagena-old-town', 'heritage'),
    ticketCny: 80,
    stayCny: 480,
    mealCny: 120,
  },
  {
    id: 'louvre-paris',
    name: '卢浮宫博物馆',
    englishName: 'Louvre Museum',
    aliases: ['巴黎卢浮宫', '卢浮宫金字塔', 'Musée du Louvre'],
    country: '法国',
    city: '巴黎',
    region: '欧洲',
    category: '人文古迹',
    grade: '5A',
    lat: 48.8606,
    lng: 2.3376,
    tagline: '王宫改建的百科全书式博物馆与玻璃金字塔入口形成古今对话',
    description:
      '世界参观量前列的艺术史殿堂，馆藏跨越古埃及至 19 世纪欧洲绘画；贝聿铭金字塔中庭重构了地下接待流线，适合博物馆建筑与城市轴线话题。',
    bestSeason: '全年（周三/周五夜场）',
    tags: ['博物馆', '艺术史', '宫廷建筑'],
    highlights: ['蒙娜丽莎厅', '古埃及馆', '拿破仑三世套房'],
    images: wmCard('louvre-paris', 'heritage'),
    ticketCny: 200,
    stayCny: 920,
    mealCny: 300,
  },
  {
    id: 'acropolis-athens',
    name: '雅典卫城',
    englishName: 'Acropolis of Athens',
    aliases: ['帕特农神庙', '希腊卫城', 'Acropolis'],
    country: '希腊',
    city: '雅典',
    region: '欧洲',
    category: '人文古迹',
    grade: '5A',
    lat: 37.9715,
    lng: 23.7267,
    tagline: '石灰岩高台上的古典神庙群是西方建筑美学的原点之一',
    description:
      '公元前 5 世纪伯里克利时代集中营造的城邦圣地，帕特农、厄瑞克忒翁与山门构成严谨轴线；夜间灯光与山下普拉卡街区形成古今层叠。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['古典建筑', '世界遗产', '城市制高点'],
    highlights: ['帕特农', '厄瑞克忒翁女像柱廊', '卫城博物馆'],
    images: wmCard('acropolis-athens', 'heritage'),
    ticketCny: 160,
    stayCny: 620,
    mealCny: 180,
  },
  {
    id: 'fitz-roy-el-chalten',
    name: '菲茨罗伊峰',
    englishName: 'Monte Fitz Roy',
    aliases: ['巴塔哥尼亚尖峰', '查尔腾镇', 'Fitz Roy'],
    country: '阿根廷',
    city: '埃尔查尔腾',
    region: '南美',
    category: '自然景观',
    grade: '精品',
    lat: -49.2717,
    lng: -73.0433,
    tagline: '花岗岩锯齿峰墙与冰川湖构成登山摄影界的「南巴塔哥尼亚」标志',
    description:
      '阿根廷冰川国家公园内尖锐山脊因气象多变常被云雾半掩；拉古纳洛斯特雷斯坦徒步线可抵达经典倒影机位，适合极限攀登史与气候话题。',
    bestSeason: '11-4 月',
    tags: ['登山', '冰川湖', '徒步'],
    highlights: ['Laguna de los Tres', '查尔腾镇补给', '托雷峰连线'],
    images: wmCard('fitz-roy-el-chalten', 'nature'),
    ticketCny: 0,
    stayCny: 520,
    mealCny: 150,
  },
  {
    id: 'sydney-harbour-bridge',
    name: '悉尼海港大桥',
    englishName: 'Sydney Harbour Bridge',
    aliases: ['悉尼大桥', '衣架桥', 'Harbour Bridge'],
    country: '澳大利亚',
    city: '悉尼',
    region: '大洋洲',
    category: '城市地标',
    grade: '精品',
    lat: -33.8523,
    lng: 151.2108,
    tagline: '钢铁拱桥与歌剧院帆顶共同框定南半球最具识别度的海港剪影',
    description:
      '1932 年通车的悬臂拱桥，可攀登拱顶俯瞰环形码头；新年烟火与帆船赛期间海港空域极具事件性，适合城市大型节庆可视化。',
    bestSeason: '9-5 月',
    tags: ['海港', '桥梁', '攀登体验'],
    highlights: ['桥拱攀登', '岩石区步行', '月神公园视角'],
    images: wmCard('sydney-harbour-bridge', 'city'),
    ticketCny: 280,
    stayCny: 920,
    mealCny: 240,
  },
  {
    id: 'tower-bridge-london',
    name: '伦敦塔桥',
    englishName: 'Tower Bridge',
    aliases: ['Tower Bridge', '泰晤士河塔桥'],
    country: '英国',
    city: '伦敦',
    region: '欧洲',
    category: '城市地标',
    grade: '精品',
    lat: 51.5055,
    lng: -0.0754,
    tagline: '维多利亚晚期巴斯克桥塔与可开启桥面定义泰晤士河下游地标',
    description:
      '1894 年投入使用的组合结构公路桥，内部蒸汽机房改建为博物馆；玻璃高空步道与塔桥升起时刻提供工程与河运史叙事。',
    bestSeason: '全年',
    tags: ['开启桥', '泰晤士河', '工业遗产'],
    highlights: ['玻璃步道', '引擎博物馆', '伦敦塔毗邻步行'],
    images: wmCard('tower-bridge-london', 'city'),
    ticketCny: 140,
    stayCny: 1120,
    mealCny: 260,
  },
  {
    id: 'big-ben-westminster',
    name: '威斯敏斯特宫与大本钟',
    englishName: 'Palace of Westminster',
    aliases: ['大本钟', '英国国会大厦', 'Big Ben'],
    country: '英国',
    city: '伦敦',
    region: '欧洲',
    category: '人文古迹',
    grade: '精品',
    lat: 51.5007,
    lng: -0.1246,
    tagline: '哥特复兴式议会建筑与钟塔构成英国民主象征空间',
    description:
      '威斯敏斯特宫沿泰晤士河展开，伊丽莎白塔（俗称大本钟）2017-2022 年修缮后重新鸣响；可与西敏寺、白厅轴线一并理解伦敦权力景观。',
    bestSeason: '全年',
    tags: ['议会建筑', '哥特复兴', '泰晤士河'],
    highlights: ['钟塔导览', '下议院旁听', '威斯敏斯特桥夜景'],
    images: wmCard('big-ben-westminster', 'heritage'),
    ticketCny: 180,
    stayCny: 1120,
    mealCny: 260,
  },
  {
    id: 'pamukkale-travertines',
    name: '棉花堡钙华梯田',
    englishName: 'Pamukkale',
    aliases: ['土耳其棉花堡', '希拉波利斯', 'Pamukkale'],
    country: '土耳其',
    city: '代尼兹利',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 37.9137,
    lng: 29.1187,
    tagline: '白色钙华阶地与罗马温泉城遗址叠合的地质与人文奇观',
    description:
      '碳酸盐沉积形成的阶梯状温泉池与古希腊罗马希拉波利斯古城并存，世界遗产；赤足行走钙华面以保护地貌，适合地质化学与旅游承载力讨论。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['钙华', '温泉', '古城遗址'],
    highlights: ['梯田温泉', '希拉波利斯剧场', '古董温泉池'],
    images: wmCard('pamukkale-travertines', 'nature'),
    ticketCny: 140,
    stayCny: 360,
    mealCny: 110,
  },
  {
    id: 'alhambra-granada',
    name: '阿尔罕布拉宫',
    englishName: 'Alhambra',
    aliases: ['格拉纳达宫城', '红宫', 'Alhambra de Granada'],
    country: '西班牙',
    city: '格拉纳达',
    region: '欧洲',
    category: '人文古迹',
    grade: '5A',
    lat: 37.1761,
    lng: -3.5882,
    tagline: '纳斯尔王朝宫殿与摩尔式庭园将几何纹样与水景推向极致',
    description:
      '13-14 世纪安达卢斯伊斯兰建筑巅峰，狮子中庭、桃金娘中庭与夏宫别墅 Generalife 花园共同构成世界遗产；夜场灯光导览强化灰泥镂空与水面倒影。',
    bestSeason: '3-5 月 / 9-11 月',
    tags: ['伊斯兰建筑', '庭园', '世界遗产'],
    highlights: ['狮子中庭', '桃金娘中庭', '阿尔拜辛区远眺'],
    images: wmCard('alhambra-granada', 'heritage'),
    ticketCny: 200,
    stayCny: 560,
    mealCny: 170,
  },
  {
    id: 'boracay-white-beach',
    name: '长滩岛白沙滩',
    englishName: 'Boracay White Beach',
    aliases: ['菲律宾长滩', 'Boracay', '白沙滩'],
    country: '菲律宾',
    city: '马来',
    region: '亚洲',
    category: '海岛度假',
    grade: '精品',
    lat: 11.9674,
    lng: 121.9248,
    tagline: '粉末状珊瑚沙与渐变海水色带塑造东南亚顶级海滩体验',
    description:
      '长约 4 公里的白沙滩分 Station 1-3 段，风帆冲浪与日落风帆活跃；经历闭岛生态修复后强调限流与污水治理，适合海岛可持续旅游案例。',
    bestSeason: '11-5 月',
    tags: ['白沙滩', '风帆', '潜水'],
    highlights: ['圣母礁岩', '普卡海滩', '布拉波滩冲浪'],
    images: wmCard('boracay-white-beach', 'coast'),
    ticketCny: 0,
    stayCny: 480,
    mealCny: 140,
  },
  {
    id: 'palawan-el-nido',
    name: '爱妮岛与巴奎特湾',
    englishName: 'El Nido',
    aliases: ['菲律宾爱妮岛', '巴拉望', 'El Nido Palawan'],
    country: '菲律宾',
    city: '爱妮岛',
    region: '亚洲',
    category: '海岛度假',
    grade: '精品',
    lat: 11.1794,
    lng: 119.3894,
    tagline: '喀斯特岛礁与泻湖跳岛线路呈现极高海水能见度与石灰岩峭壁',
    description:
      '巴拉望北部海岸国家公园群，A/B/C/D 线跳岛串联小泻湖、秘密海滩与蛇岛沙洲；生态脆弱区需遵守浮潜规范与塑料减量。',
    bestSeason: '11-5 月',
    tags: ['跳岛', '泻湖', '喀斯特海岸'],
    highlights: ['大泻湖', '秘密海滩', '纳克潘海滩'],
    images: wmCard('palawan-el-nido', 'coast'),
    ticketCny: 220,
    stayCny: 420,
    mealCny: 120,
  },
  {
    id: 'geirangerfjord',
    name: '盖朗厄尔峡湾',
    englishName: 'Geirangerfjord',
    aliases: ['挪威盖湾', '七姐妹瀑布', 'Geiranger'],
    country: '挪威',
    city: '盖朗厄尔',
    region: '欧洲',
    category: '自然景观',
    grade: '5A',
    lat: 62.1048,
    lng: 7.2058,
    tagline: '深邃 U 型峡湾与多级瀑布构成北欧峡湾世界遗产名片',
    description:
      '与纳柔依峡湾并列列入世界遗产，陡峭岩壁上的废弃农场与七姐妹瀑布展现冰川侵蚀史；Flydalsjuvet 与老鹰之路观景台是经典公路旅行节点。',
    bestSeason: '5-9 月',
    tags: ['峡湾', '邮轮', '公路观景台'],
    highlights: ['七姐妹瀑布', 'Flydalsjuvet', '老鹰之路'],
    images: wmCard('geirangerfjord', 'nature'),
    ticketCny: 0,
    stayCny: 980,
    mealCny: 220,
  },
  {
    id: 'west-lake-hangzhou',
    name: '杭州西湖',
    englishName: 'West Lake',
    aliases: ['西湖', '杭州西湖风景区', 'West Lake Hangzhou'],
    country: '中国',
    city: '杭州',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 30.2489,
    lng: 120.1453,
    tagline: '一湖两堤三岛与环湖文化史迹构成江南湖山城市范本',
    description:
      '文化景观世界遗产，苏堤春晓、断桥残雪等「西湖十景」与白堤、孤山史迹交织；环湖公交与游船便于串联灵隐、龙井等片区，适合人文与自然叠合浏览。',
    bestSeason: '3-5 月 / 9-11 月',
    tags: ['世界遗产', '湖泊', '江南园林'],
    highlights: ['三潭印月', '苏堤', '雷峰塔'],
    images: wmCard('west-lake-hangzhou', 'nature'),
    ticketCny: 0,
    stayCny: 480,
    mealCny: 160,
  },
  {
    id: 'jiuzhaigou-valley',
    name: '九寨沟',
    englishName: 'Jiuzhaigou Valley',
    aliases: ['九寨沟风景区', '四川九寨沟', 'Jiuzhaigou'],
    country: '中国',
    city: '阿坝',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 33.26,
    lng: 103.918,
    tagline: '钙华彩池与原始森林叠出高海拔喀斯特水景极致',
    description:
      '世界自然遗产，Y 型沟谷串联长海、五花海、诺日朗瀑布等；高海拔湖泊透明度极高，秋季彩林与冬季蓝冰各具辨识度，需注意高原反应与客流预约。',
    bestSeason: '9-11 月（彩林）/ 冬季雪景',
    tags: ['世界遗产', '彩池', '瀑布群'],
    highlights: ['五花海', '诺日朗瀑布', '长海'],
    images: wmCard('jiuzhaigou-valley', 'nature'),
    ticketCny: 259,
    stayCny: 420,
    mealCny: 120,
  },
  {
    id: 'huanglong-scenic',
    name: '黄龙风景名胜区',
    englishName: 'Huanglong Scenic Area',
    aliases: ['四川黄龙', '黄龙五彩池', 'Huanglong'],
    country: '中国',
    city: '松潘',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 32.7542,
    lng: 103.8244,
    tagline: '钙华梯田与雪峰背景形成「人间瑶池」式蓝绿阶地',
    description:
      '与九寨沟同属岷山山脉世界自然遗产片区，地表钙华沉积形成层叠彩池；索道与栈道结合，生态脆弱需严格沿指定路线游览。',
    bestSeason: '9-10 月',
    tags: ['钙华池', '世界遗产', '高山'],
    highlights: ['五彩池', '黄龙寺', '雪宝顶远眺'],
    images: wmCard('huanglong-scenic', 'nature'),
    ticketCny: 170,
    stayCny: 380,
    mealCny: 100,
  },
  {
    id: 'mount-tai-taishan',
    name: '泰山',
    englishName: 'Mount Tai',
    aliases: ['东岳泰山', '泰安泰山', 'Taishan'],
    country: '中国',
    city: '泰安',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 36.2503,
    lng: 117.1011,
    tagline: '五岳之首承载封禅史迹与摩崖石刻的复合山岳遗产',
    description:
      '世界自然与文化双遗产，红门、中天门至南天门经典登山轴线串联岱庙；日出云海与历代题刻体现「泰山安，四海皆安」的文化地理意象。',
    bestSeason: '4-6 月 / 9-11 月',
    tags: ['五岳', '登山', '世界遗产'],
    highlights: ['南天门', '玉皇顶', '岱庙'],
    images: wmCard('mount-tai-taishan', 'nature'),
    ticketCny: 115,
    stayCny: 320,
    mealCny: 90,
  },
  {
    id: 'mount-hua-huashan',
    name: '华山',
    englishName: 'Mount Hua',
    aliases: ['西岳华山', '陕西华山', 'Huashan'],
    country: '中国',
    city: '华阴',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 34.4844,
    lng: 110.0919,
    tagline: '花岗岩绝壁与长空栈道塑造极限登山体验',
    description:
      '五岳中以险峻著称，北峰、西峰索道与苍龙岭、鹞子翻身等险段闻名；夜爬观日出传统浓厚，需评估体力与天气封山信息。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['险峰', '索道', '日出'],
    highlights: ['长空栈道', '西峰日落', '北峰云台'],
    images: wmCard('mount-hua-huashan', 'nature'),
    ticketCny: 160,
    stayCny: 280,
    mealCny: 85,
  },
  {
    id: 'temple-of-heaven-beijing',
    name: '天坛公园',
    englishName: 'Temple of Heaven',
    aliases: ['天坛', '祈年殿', '北京天坛'],
    country: '中国',
    city: '北京',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 39.8822,
    lng: 116.4066,
    tagline: '明清皇家祭天建筑群以圆形祈年殿象征「天圆地方」礼制空间',
    description:
      '世界遗产，圜丘、皇穹宇与祈年殿构成南北轴线；声学回音壁与祭天仪轨展示古代宇宙观，清晨市民晨练亦是当代城市公共空间一景。',
    bestSeason: '4-5 月 / 9-10 月',
    tags: ['祭天', '古建筑', '世界遗产'],
    highlights: ['祈年殿', '圜丘坛', '回音壁'],
    images: wmCard('temple-of-heaven-beijing', 'heritage'),
    ticketCny: 34,
    stayCny: 420,
    mealCny: 150,
  },
  {
    id: 'summer-palace-beijing',
    name: '颐和园',
    englishName: 'Summer Palace',
    aliases: ['北京颐和园', '昆明湖', '万寿山'],
    country: '中国',
    city: '北京',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 39.9999,
    lng: 116.2755,
    tagline: '皇家园林借景西山与昆明湖形成中国古典园林巅峰之作',
    description:
      '世界文化遗产，长廊728米彩绘、石舫、十七孔桥与谐趣园等节点体现「虽由人作，宛自天开」；冬季昆明湖冰上活动与夏季游船形成季节反差。',
    bestSeason: '四季',
    tags: ['皇家园林', '世界遗产', '昆明湖'],
    highlights: ['佛香阁', '长廊', '十七孔桥'],
    images: wmCard('summer-palace-beijing', 'heritage'),
    ticketCny: 30,
    stayCny: 420,
    mealCny: 150,
  },
  {
    id: 'potala-palace-lhasa',
    name: '布达拉宫',
    englishName: 'Potala Palace',
    aliases: ['拉萨布达拉宫', '布达拉', 'Potala'],
    country: '中国',
    city: '拉萨',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 29.655,
    lng: 91.1185,
    tagline: '玛布日山巅的宫堡式建筑群是藏式宗教艺术的象征性地标',
    description:
      '世界文化遗产，白宫与红宫分层错落，灵塔殿与壁画系统展示政教合一历史；参观需预约且限时爬坡，注意高原适应与文物保护规定。',
    bestSeason: '5-10 月',
    tags: ['藏传佛教', '宫堡', '世界遗产'],
    highlights: ['白宫', '红宫', '德央夏广场'],
    images: wmCard('potala-palace-lhasa', 'heritage'),
    ticketCny: 200,
    stayCny: 380,
    mealCny: 120,
  },
  {
    id: 'wudang-mountains',
    name: '武当山',
    englishName: 'Wudang Mountains',
    aliases: ['十堰武当山', '武当山风景区', 'Wudangshan'],
    country: '中国',
    city: '十堰',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 32.4008,
    lng: 111.0049,
    tagline: '道教名山与明代宫观建筑群体现「道法自然」的山地聚落',
    description:
      '世界文化遗产，南岩宫、紫霄宫与金顶铜殿沿登山径分布；太极拳发源地文化标签与丹霞峰丛共同构成武术朝圣与自然观光双主题。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['道教', '古建筑群', '武术文化'],
    highlights: ['金顶', '南岩宫', '太子坡'],
    images: wmCard('wudang-mountains', 'heritage'),
    ticketCny: 179,
    stayCny: 320,
    mealCny: 95,
  },
  {
    id: 'mount-wutai',
    name: '五台山',
    englishName: 'Mount Wutai',
    aliases: ['山西五台山', '清凉山', 'Wutai Mountain'],
    country: '中国',
    city: '忻州',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 39.081,
    lng: 113.5934,
    tagline: '华北屋脊上的汉藏佛教寺院群呈现山地朝圣网络',
    description:
      '世界文化遗产，台怀镇为中心辐射显通寺、塔院寺大白塔等古刹；朝台车与徒步五台传统并存，夏季凉爽冬季严寒需备防寒装备。',
    bestSeason: '6-9 月',
    tags: ['佛教名山', '朝圣', '世界遗产'],
    highlights: ['大白塔', '显通寺', '菩萨顶'],
    images: wmCard('mount-wutai', 'heritage'),
    ticketCny: 135,
    stayCny: 300,
    mealCny: 80,
  },
  {
    id: 'leshan-giant-buddha',
    name: '乐山大佛',
    englishName: 'Leshan Giant Buddha',
    aliases: ['峨眉山乐山大佛', '凌云大佛', 'Leshan Buddha'],
    country: '中国',
    city: '乐山',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 29.5447,
    lng: 103.7717,
    tagline: '临江摩崖弥勒坐像与三江汇流构成巨型石刻与水利减灾结合的奇观',
    description:
      '世界文化与自然双遗产组成部分，通高 71 米的唐代石刻依凌云山开凿；游船江面仰观与九曲栈道近观视角差异显著，汛期注意水位与开放信息。',
    bestSeason: '3-5 月 / 9-11 月',
    tags: ['摩崖石刻', '三江汇流', '世界遗产'],
    highlights: ['九曲栈道', '凌云寺', '江游船观佛'],
    images: wmCard('leshan-giant-buddha', 'heritage'),
    ticketCny: 80,
    stayCny: 260,
    mealCny: 90,
  },
  {
    id: 'longmen-grottoes-luoyang',
    name: '龙门石窟',
    englishName: 'Longmen Grottoes',
    aliases: ['洛阳龙门', '伊阙石窟', 'Longmen'],
    country: '中国',
    city: '洛阳',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 34.5552,
    lng: 112.4641,
    tagline: '伊河两岸北魏至唐的窟龛石刻序列展现中国石窟艺术高峰',
    description:
      '世界文化遗产，奉先寺卢舍那大佛与万佛洞等代表皇家赞助与民间功德并行；夜游灯光与香山寺白居易墓园可延伸人文线路。',
    bestSeason: '春秋',
    tags: ['石窟', '北魏唐', '世界遗产'],
    highlights: ['奉先寺', '宾阳三洞', '香山寺'],
    images: wmCard('longmen-grottoes-luoyang', 'heritage'),
    ticketCny: 90,
    stayCny: 280,
    mealCny: 85,
  },
  {
    id: 'yungang-grottoes-datong',
    name: '云冈石窟',
    englishName: 'Yungang Grottoes',
    aliases: ['大同云冈', '云冈', 'Yungang'],
    country: '中国',
    city: '大同',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 40.1119,
    lng: 113.1225,
    tagline: '北魏皇家窟寺群以昙曜五窟为代表奠定中原石窟样式源头',
    description:
      '世界文化遗产，主要洞窟 45 个，第20窟露天大佛最具标识度；砂岩风化敏感，参观时勿触摸雕刻并关注景区分时段预约政策。',
    bestSeason: '4-10 月',
    tags: ['石窟', '北魏', '世界遗产'],
    highlights: ['第20窟', '第5-6窟', '云冈博物馆'],
    images: wmCard('yungang-grottoes-datong', 'heritage'),
    ticketCny: 120,
    stayCny: 240,
    mealCny: 70,
  },
  {
    id: 'mogao-caves-dunhuang',
    name: '莫高窟',
    englishName: 'Mogao Caves',
    aliases: ['敦煌莫高窟', '千佛洞', 'Mogao'],
    country: '中国',
    city: '敦煌',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 40.0415,
    lng: 94.8079,
    tagline: '戈壁断崖上的千年窟室与壁画藏经洞定义丝路艺术宝库',
    description:
      '世界文化遗产，十六国至元代连续营造，壁画与彩塑反映多民族佛教艺术；普窟与特窟分级开放，数字展示中心先行观影有助理解洞窟语境。',
    bestSeason: '5-10 月',
    tags: ['敦煌', '壁画', '世界遗产'],
    highlights: ['九层楼', '藏经洞陈列', '数字中心'],
    images: wmCard('mogao-caves-dunhuang', 'heritage'),
    ticketCny: 238,
    stayCny: 320,
    mealCny: 90,
  },
  {
    id: 'mount-wuyi',
    name: '武夷山',
    englishName: 'Mount Wuyi',
    aliases: ['福建武夷山', '武夷岩茶', 'Wuyishan'],
    country: '中国',
    city: '南平',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 27.7402,
    lng: 118.0222,
    tagline: '丹霞峰丛与九曲溪竹筏漂流构成闽北山水与茶文化核心场景',
    description:
      '世界自然与文化双遗产，天游峰俯瞰溪流曲行，大红袍母树与下梅古村延伸茶旅；夏季竹筏旺季节点需提前订票。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['丹霞', '竹筏', '岩茶'],
    highlights: ['九曲溪', '天游峰', '大红袍景区'],
    images: wmCard('mount-wuyi', 'nature'),
    ticketCny: 140,
    stayCny: 300,
    mealCny: 95,
  },
  {
    id: 'lijiang-old-town-china',
    name: '丽江古城',
    englishName: 'Old Town of Lijiang',
    aliases: ['丽江大研古城', '云南丽江', 'Lijiang'],
    country: '中国',
    city: '丽江',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 26.8721,
    lng: 100.2299,
    tagline: '纳西族土木结构与水系街巷在山地坝子中延续茶马古道记忆',
    description:
      '世界文化遗产，四方街辐射五花石巷道，黑龙潭远眺玉龙雪山；古城维护费政策与客流管理以景区公告为准，夜间酒吧街与清晨静谧反差鲜明。',
    bestSeason: '3-5 月 / 9-11 月',
    tags: ['古城', '纳西文化', '世界遗产'],
    highlights: ['四方街', '木府', '狮子山万古楼'],
    images: wmCard('lijiang-old-town-china', 'heritage'),
    ticketCny: 50,
    stayCny: 360,
    mealCny: 100,
  },
  {
    id: 'suzhou-lingering-garden',
    name: '苏州园林（留园）',
    englishName: 'Lingering Garden',
    aliases: ['留园', '苏州古典园林', 'Lingering Garden Suzhou'],
    country: '中国',
    city: '苏州',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 31.3173,
    lng: 120.5925,
    tagline: '以建筑空间序列与太湖石冠云峰著称的清代私家园林代表',
    description:
      '中国古典园林世界遗产组成部分，分区明确、游线曲折；与拙政园、网师园等可组合一日游，旺季建议网络预约错峰入园。',
    bestSeason: '春秋',
    tags: ['江南园林', '世界遗产', '太湖石'],
    highlights: ['冠云峰', '五峰仙馆', '濠濮亭'],
    images: wmCard('suzhou-lingering-garden', 'heritage'),
    ticketCny: 55,
    stayCny: 380,
    mealCny: 120,
  },
  {
    id: 'zhouzhuang-water-town',
    name: '周庄古镇',
    englishName: 'Zhouzhuang Water Town',
    aliases: ['昆山周庄', '中国第一水乡', 'Zhouzhuang'],
    country: '中国',
    city: '昆山',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 31.1167,
    lng: 120.8447,
    tagline: '双桥与沈厅张厅定义江南水乡高密度水巷聚落意象',
    description:
      '昆山水乡古镇代表，摇橹船穿行市河，沈万三传说与明清民居串联商业与宗族史；夜游灯光与昼间写生人群形成不同氛围。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['水乡', '古镇', '摇橹船'],
    highlights: ['双桥', '沈厅', '南湖秋月园'],
    images: wmCard('zhouzhuang-water-town', 'heritage'),
    ticketCny: 100,
    stayCny: 340,
    mealCny: 110,
  },
  {
    id: 'huangguoshu-waterfall',
    name: '黄果树瀑布',
    englishName: 'Huangguoshu Waterfall',
    aliases: ['黄果树大瀑布', '贵州黄果树', 'Huangguoshu'],
    country: '中国',
    city: '安顺',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 25.7319,
    lng: 105.8297,
    tagline: '喀斯特河谷中的多级瀑布群与穿水帘洞体验兼具声量与尺度震撼',
    description:
      '世界自然遗产荔波喀斯特延伸片区外的独立 5A 集群，大瀑布、陡坡塘、天星桥分段游览；丰水期水雾大需备雨衣，枯水期可进入水帘洞近观。',
    bestSeason: '6-10 月丰水',
    tags: ['瀑布', '喀斯特', '水帘洞'],
    highlights: ['大瀑布', '天星桥', '陡坡塘'],
    images: wmCard('huangguoshu-waterfall', 'nature'),
    ticketCny: 160,
    stayCny: 260,
    mealCny: 80,
  },
  {
    id: 'stone-forest-kunming',
    name: '石林风景区',
    englishName: 'Stone Forest',
    aliases: ['云南石林', '路南石林', 'Shilin'],
    country: '中国',
    city: '石林',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 24.8103,
    lng: 103.3256,
    tagline: '剑状喀斯特石柱群如森林拔地而起，阿诗玛传说强化人文联想',
    description:
      '世界自然遗产云南石林核心景区，大石林迷宫式穿行与小石林精致石景并存；彝族撒尼文化与民族歌舞表演常作为行程延伸。',
    bestSeason: '全年',
    tags: ['喀斯特', '石柱', '彝族文化'],
    highlights: ['大石林', '小石林', '步哨山'],
    images: wmCard('stone-forest-kunming', 'nature'),
    ticketCny: 130,
    stayCny: 280,
    mealCny: 75,
  },
  {
    id: 'mount-emei-scenic',
    name: '峨眉山',
    englishName: 'Mount Emei',
    aliases: ['四川峨眉山', '峨眉金顶', 'Emei Mountain'],
    country: '中国',
    city: '乐山',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 29.5202,
    lng: 103.3363,
    tagline: '普贤道场与亚热带至寒带垂直植被带共构佛教名山生态走廊',
    description:
      '世界文化与自然双遗产，报国寺至雷洞坪车索结合徒步，金顶十方普贤像与云海佛光现象知名度高；山区猴群需注意财物安全。',
    bestSeason: '春秋',
    tags: ['佛教名山', '金顶', '生态垂直带'],
    highlights: ['金顶', '清音阁', '生态猴区'],
    images: wmCard('mount-emei-scenic', 'nature'),
    ticketCny: 160,
    stayCny: 320,
    mealCny: 90,
  },
  {
    id: 'mount-putuo',
    name: '普陀山',
    englishName: 'Mount Putuo',
    aliases: ['舟山普陀山', '南海观音', 'Putuo Mountain'],
    country: '中国',
    city: '舟山',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 30.0155,
    lng: 122.3963,
    tagline: '观音道场与岛礁海岸结合的海上佛国朝圣目的地',
    description:
      '中国佛教四大名山之一，轮渡衔接朱家尖码头，普济、法雨、慧济寺与南海观音立像构成核心朝线；台风季需关注停航信息。',
    bestSeason: '4-10 月',
    tags: ['海岛朝圣', '观音道场', '禅寺'],
    highlights: ['南海观音', '普济寺', '佛顶山索道'],
    images: wmCard('mount-putuo', 'heritage'),
    ticketCny: 160,
    stayCny: 400,
    mealCny: 100,
  },
  {
    id: 'qinghai-lake-scenic',
    name: '青海湖',
    englishName: 'Qinghai Lake',
    aliases: ['青海湖景区', '高原蓝宝石', 'Qinghai Hu'],
    country: '中国',
    city: '海北/海南',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 36.8899,
    lng: 100.1546,
    tagline: '中国最大咸水湖与环湖油菜花海、候鸟迁徙构成高原生态名片',
    description:
      '国际重要湿地，夏季环湖骑行与二郎剑等景区成熟；海拔约 3200 米注意防晒与高反，环湖藏族牧区请尊重宗教与草场边界。',
    bestSeason: '6-8 月（油菜花/候鸟）',
    tags: ['高原湖', '骑行', '候鸟'],
    highlights: ['二郎剑', '鸟岛季', '环湖西路'],
    images: wmCard('qinghai-lake-scenic', 'nature'),
    ticketCny: 90,
    stayCny: 280,
    mealCny: 85,
  },
  {
    id: 'kanas-lake-scenic',
    name: '喀纳斯',
    englishName: 'Kanas Lake',
    aliases: ['喀纳斯湖', '新疆喀纳斯', '禾木白哈巴'],
    country: '中国',
    city: '布尔津',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 48.7208,
    lng: 87.0378,
    tagline: '阿尔泰山深处的冰川堰塞湖与泰加林秋色塑造北疆摄影顶流',
    description:
      '国家级自然保护地内核心景观，观鱼台俯瞰湖色随光线变化；禾木、白哈巴图瓦村落与秋季金黄白桦林常联游，冬季冰雪封路政策需提前查询。',
    bestSeason: '6 月中-10 月初',
    tags: ['高山湖', '秋色', '图瓦村落'],
    highlights: ['观鱼台', '三湾徒步', '禾木村'],
    images: wmCard('kanas-lake-scenic', 'nature'),
    ticketCny: 230,
    stayCny: 420,
    mealCny: 110,
  },
  {
    id: 'heaven-lake-changbai',
    name: '长白山天池',
    englishName: 'Heaven Lake',
    aliases: ['长白山', '白头山天池', 'Changbai Mountain'],
    country: '中国',
    city: '延边',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 42.0069,
    lng: 128.0574,
    tagline: '火山口湖与垂直植被带、温泉群共构东北亚高山生态样本',
    description:
      '世界自然保留地，北坡西坡南坡开放程度不同，天池常云雾遮挡需多次尝试；聚龙泉温泉蛋与地下森林徒步为经典体验。',
    bestSeason: '6-9 月 / 冬季滑雪',
    tags: ['火山湖', '温泉', '森林'],
    highlights: ['天池', '长白瀑布', '地下森林'],
    images: wmCard('heaven-lake-changbai', 'nature'),
    ticketCny: 190,
    stayCny: 360,
    mealCny: 95,
  },
  {
    id: 'yading-nature-reserve',
    name: '稻城亚丁',
    englishName: 'Yading Nature Reserve',
    aliases: ['亚丁景区', '香格里拉镇', '三神山'],
    country: '中国',
    city: '稻城',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 28.4464,
    lng: 100.3347,
    tagline: '仙乃日、央迈勇、夏诺多吉三座神山与高山海子构成香格里拉叙事核心',
    description:
      '大香格里拉生态旅游区核心，洛绒牛场至五色海、牛奶海徒步海拔爬升大；高反预防与马帮预约需提前规划，秋季晴天率利于摄影。',
    bestSeason: '9-10 月',
    tags: ['神山', '徒步', '高山海子'],
    highlights: ['洛绒牛场', '牛奶海', '冲古寺'],
    images: wmCard('yading-nature-reserve', 'nature'),
    ticketCny: 266,
    stayCny: 380,
    mealCny: 100,
  },
  {
    id: 'mount-lushan',
    name: '庐山',
    englishName: 'Mount Lu',
    aliases: ['江西庐山', '匡庐', 'Lushan'],
    country: '中国',
    city: '九江',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 29.5767,
    lng: 115.9883,
    tagline: '避暑胜地与政治名山双重身份叠加在云雾瀑布花岗岩台地之上',
    description:
      '世界文化景观遗产，牯岭镇为山顶生活枢纽，三叠泉、五老峰、美庐别墅等节点串联自然与人文；景区观光车串联分散景点。',
    bestSeason: '5-9 月避暑',
    tags: ['避暑', '瀑布', '近代史建筑'],
    highlights: ['三叠泉', '五老峰', '牯岭街'],
    images: wmCard('mount-lushan', 'nature'),
    ticketCny: 160,
    stayCny: 320,
    mealCny: 90,
  },
  {
    id: 'yandang-mountain',
    name: '雁荡山',
    englishName: 'Yandang Mountain',
    aliases: ['浙江雁荡山', '东南第一山', 'Yandangshan'],
    country: '中国',
    city: '乐清',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 28.3694,
    lng: 121.0603,
    tagline: '流纹岩峰丛与夜幕灵峰剪影构成浙东海岸山脉的识别性景观',
    description:
      '世界地质公园，灵峰夜景轮廓想象、大龙湫单级瀑布与方洞栈道体现火山岩侵蚀地貌；雨季瀑布水量充沛但步道湿滑。',
    bestSeason: '春秋',
    tags: ['流纹岩', '夜景剪影', '瀑布'],
    highlights: ['灵峰夜景', '大龙湫', '灵岩飞渡'],
    images: wmCard('yandang-mountain', 'nature'),
    ticketCny: 45,
    stayCny: 260,
    mealCny: 80,
  },
  {
    id: 'gulangyu-island',
    name: '鼓浪屿',
    englishName: 'Gulangyu Island',
    aliases: ['厦门鼓浪屿', '钢琴之岛', 'Gulangyu'],
    country: '中国',
    city: '厦门',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 24.4485,
    lng: 118.0658,
    tagline: '无机动车步行岛上的万国建筑博览与钢琴文化共生遗产社区',
    description:
      '世界文化遗产，日光岩瞰厦门本岛，菽庄花园借海为园；轮渡预约制与上岛客流控制常态化，适合慢行与建筑细部摄影。',
    bestSeason: '10-4 月（避台风季）',
    tags: ['步行岛', '近代建筑', '世界遗产'],
    highlights: ['日光岩', '菽庄花园', '风琴博物馆'],
    images: wmCard('gulangyu-island', 'heritage'),
    ticketCny: 100,
    stayCny: 400,
    mealCny: 120,
  },
  {
    id: 'three-gorges-dam',
    name: '三峡大坝旅游区',
    englishName: 'Three Gorges Dam',
    aliases: ['三峡大坝', '宜昌三峡', '三峡工程'],
    country: '中国',
    city: '宜昌',
    region: '亚洲',
    category: '城市地标',
    grade: '5A',
    lat: 30.8231,
    lng: 111.0034,
    tagline: '长江干流巨型水利枢纽与坛子岭俯瞰展示当代工程尺度',
    description:
      '国家 5A 水利观光景区，坛子岭、185 平台、截流纪念园等节点解读防洪、发电与航运功能；升船机体验项目需另购票并以景区安排为准。',
    bestSeason: '春秋',
    tags: ['水利工程', '长江', '工业旅游'],
    highlights: ['坛子岭', '185 观景', '截流园'],
    images: wmCard('three-gorges-dam', 'city'),
    ticketCny: 0,
    stayCny: 220,
    mealCny: 70,
  },
  {
    id: 'dazu-rock-carvings',
    name: '大足石刻',
    englishName: 'Dazu Rock Carvings',
    aliases: ['重庆大足', '宝顶山石刻', 'Dazu'],
    country: '中国',
    city: '重庆',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 29.7526,
    lng: 105.7844,
    tagline: '唐宋时期儒释道三教合一石窟群体现巴蜀民间信仰高度',
    description:
      '世界文化遗产，宝顶山圆觉洞、北山观音像等以生活化叙事与精细镂刻著称；与敦煌莫高窟高原风格形成南方石窟对比样本。',
    bestSeason: '全年',
    tags: ['石窟', '唐宋', '世界遗产'],
    highlights: ['宝顶山', '北山', '博物馆'],
    images: wmCard('dazu-rock-carvings', 'heritage'),
    ticketCny: 115,
    stayCny: 260,
    mealCny: 75,
  },
  {
    id: 'pingyao-ancient-city',
    name: '平遥古城',
    englishName: 'Pingyao Ancient City',
    aliases: ['山西平遥', '平遥城墙', 'Pingyao'],
    country: '中国',
    city: '晋中',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 37.1983,
    lng: 112.1775,
    tagline: '明清县城完整格局与票号金融史共筑晋商文化空间标本',
    description:
      '世界文化遗产，城墙周长约6公里，日升昌票号、县衙、文庙等节点密集；《又见平遥》情境演出为夜间消费延伸。',
    bestSeason: '4-6 月 / 9-10 月',
    tags: ['古城墙', '晋商', '世界遗产'],
    highlights: ['城墙漫步', '日升昌', '县衙'],
    images: wmCard('pingyao-ancient-city', 'heritage'),
    ticketCny: 125,
    stayCny: 240,
    mealCny: 70,
  },
  {
    id: 'chengde-mountain-resort',
    name: '承德避暑山庄及外八庙',
    englishName: 'Chengde Mountain Resort',
    aliases: ['避暑山庄', '承德外八庙', 'Chengde'],
    country: '中国',
    city: '承德',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 40.9781,
    lng: 117.9388,
    tagline: '清代夏宫园林与藏式寺庙群体现多民族帝国统治的空间修辞',
    description:
      '世界文化遗产，山庄湖区、平原、山峦三区模仿江南与塞外景观；普陀宗乘之庙「小布达拉宫」与须弥福寿之庙金顶极具视觉记忆。',
    bestSeason: '5-9 月',
    tags: ['皇家园林', '藏式寺庙', '世界遗产'],
    highlights: ['宫殿区', '普陀宗乘之庙', '磬锤峰'],
    images: wmCard('chengde-mountain-resort', 'heritage'),
    ticketCny: 130,
    stayCny: 220,
    mealCny: 75,
  },
  {
    id: 'shennongjia-scenic',
    name: '神农架',
    englishName: 'Shennongjia',
    aliases: ['神农架国家公园', '华中屋脊', '野人传说'],
    country: '中国',
    city: '神农架林区',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 31.7449,
    lng: 110.6758,
    tagline: '亚高山原始森林与金丝猴栖息地构成中纬度生物多样性热点',
    description:
      '世界自然遗产，大九湖湿地晨雾、神农顶海拔3105米与板壁岩石林为经典节点；气候多变需备雨具，部分区域对自驾有限行规定。',
    bestSeason: '5-10 月',
    tags: ['原始森林', '湿地', '金丝猴'],
    highlights: ['大九湖', '神农顶', '天燕景区'],
    images: wmCard('shennongjia-scenic', 'nature'),
    ticketCny: 269,
    stayCny: 300,
    mealCny: 85,
  },
  {
    id: 'shaolin-temple-scenic',
    name: '嵩山少林寺',
    englishName: 'Shaolin Monastery',
    aliases: ['少林寺', '嵩山少林', 'Shaolin'],
    country: '中国',
    city: '登封',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 34.5081,
    lng: 112.9474,
    tagline: '禅宗祖庭与武术表演产业共塑全球辨识度的中国寺庙 IP',
    description:
      '世界文化遗产「天地之中」历史建筑群组成部分，常住院、塔林与初祖庵承载佛教与武术传统；武术馆演出时间与门票以景区当日公告为准。',
    bestSeason: '春秋',
    tags: ['禅宗', '武术', '塔林'],
    highlights: ['常住院', '塔林', '武术表演'],
    images: wmCard('shaolin-temple-scenic', 'heritage'),
    ticketCny: 80,
    stayCny: 220,
    mealCny: 65,
  },
  {
    id: 'qufu-confucius-temple',
    name: '曲阜三孔',
    englishName: 'Temple of Confucius in Qufu',
    aliases: ['孔庙孔府孔林', '曲阜', 'Qufu'],
    country: '中国',
    city: '曲阜',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 35.5969,
    lng: 116.9912,
    tagline: '儒家圣城以孔庙轴线与孔府宅第、孔林墓葬群形成礼制空间完整链',
    description:
      '世界文化遗产，历代帝王祭孔中心，碑刻林立；孔府展示衍圣公府邸生活，孔林古柏参天。春节祭孔大典与开城仪式具仪式感。',
    bestSeason: '春秋',
    tags: ['儒家', '礼制建筑', '世界遗产'],
    highlights: ['孔庙大成殿', '孔府', '孔林'],
    images: wmCard('qufu-confucius-temple', 'heritage'),
    ticketCny: 140,
    stayCny: 200,
    mealCny: 60,
  },
  {
    id: 'wuzhen-water-town',
    name: '乌镇',
    englishName: 'Wuzhen',
    aliases: ['桐乡乌镇', '乌镇西栅', 'Wuzhen'],
    country: '中国',
    city: '桐乡',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 30.7483,
    lng: 120.4899,
    tagline: '大运河古镇经整体策展改造成为水乡夜游与戏剧节标杆',
    description:
      '世界互联网大会永久会址所在地，东栅生活气息与西栅夜景灯光、摇橹船服务成熟；木心美术馆与戏剧节延伸当代艺术体验。',
    bestSeason: '春秋',
    tags: ['水乡', '夜游', '戏剧节'],
    highlights: ['西栅夜景', '木心美术馆', '茅盾故居'],
    images: wmCard('wuzhen-water-town', 'heritage'),
    ticketCny: 190,
    stayCny: 400,
    mealCny: 110,
  },
  {
    id: 'hukou-waterfall-yellow-river',
    name: '黄河壶口瀑布',
    englishName: 'Hukou Waterfall',
    aliases: ['壶口瀑布', '晋陕大峡谷壶口', 'Hukou'],
    country: '中国',
    city: '吉县/宜川',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 36.0711,
    lng: 110.4425,
    tagline: '黄河干流骤然收束形成的金色水墙与晋陕两岸不同观瀑视角',
    description:
      '陕西侧与山西侧分属不同景区管理，丰水期气势雄浑、枯水期部分河床裸露；「黄河大合唱」文化意象与龙洞仰观为经典体验。',
    bestSeason: '4-5 月桃花汛 / 7-9 月',
    tags: ['黄河', '瀑布', '峡谷'],
    highlights: ['龙洞观瀑', '孟门山', '两岸观景台'],
    images: wmCard('hukou-waterfall-yellow-river', 'nature'),
    ticketCny: 100,
    stayCny: 200,
    mealCny: 60,
  },
  {
    id: 'mount-sanqing',
    name: '三清山',
    englishName: 'Mount Sanqing',
    aliases: ['江西三清山', '道教名山', 'Sanqingshan'],
    country: '中国',
    city: '上饶',
    region: '亚洲',
    category: '自然景观',
    grade: '5A',
    lat: 28.9156,
    lng: 118.0668,
    tagline: '花岗岩峰柱与云海佛光频繁出现的道教世界遗产山岳',
    description:
      '世界自然遗产，巨蟒出山、东方女神等象形石景与高空栈道系统结合；山上住宿有限，一日游索道衔接需排队预案。',
    bestSeason: '5-6 月 / 9-11 月',
    tags: ['花岗岩峰林', '道教', '栈道'],
    highlights: ['南清园', '西海岸栈道', '三清宫'],
    images: wmCard('mount-sanqing', 'nature'),
    ticketCny: 120,
    stayCny: 260,
    mealCny: 75,
  },
  {
    id: 'kaifeng-qingming-river-park',
    name: '清明上河园',
    englishName: 'Qingming Riverside Landscape Garden',
    aliases: ['开封清明上河园', '汴梁', '清明上河图'],
    country: '中国',
    city: '开封',
    region: '亚洲',
    category: '人文古迹',
    grade: '5A',
    lat: 34.8156,
    lng: 114.3414,
    tagline: '以《清明上河图》为母题的主题公园再现北宋市井生活场景',
    description:
      '大型宋文化沉浸式景区，虹桥、勾栏瓦肆与日间实景演出《大宋·东京梦华》强化穿越体验；与开封府、铁塔公园可组合汴梁古城线路。',
    bestSeason: '春秋',
    tags: ['宋文化', '主题公园', '实景演出'],
    highlights: ['虹桥', '东京梦华', '汴河漕运'],
    images: wmCard('kaifeng-qingming-river-park', 'heritage'),
    ticketCny: 120,
    stayCny: 200,
    mealCny: 70,
  },
];

export const ORIGIN_PRESETS: readonly OriginPreset[] = [
  { id: 'beijing', city: '北京', lat: 39.9042, lng: 116.4074, budgetBand: 'medium' },
  { id: 'shanghai', city: '上海', lat: 31.2304, lng: 121.4737, budgetBand: 'medium' },
  { id: 'guangzhou', city: '广州', lat: 23.1291, lng: 113.2644, budgetBand: 'medium' },
  { id: 'hongkong', city: '香港', lat: 22.3193, lng: 114.1694, budgetBand: 'high' },
  { id: 'paris', city: '巴黎', lat: 48.8566, lng: 2.3522, budgetBand: 'high' },
  { id: 'newyork', city: '纽约', lat: 40.7128, lng: -74.006, budgetBand: 'high' },
  { id: 'sydney', city: '悉尼', lat: -33.8688, lng: 151.2093, budgetBand: 'high' },
];

export const CATEGORY_OPTIONS = ['全部', '自然景观', '人文古迹', '城市地标', '海岛度假'] as const;
export const REGION_OPTIONS = ['全部', ...new Set(DESTINATION_POINTS.map((point) => point.region))] as const;
export const SEARCH_EXAMPLES = ['法国浪漫铁塔', '杭州西湖', '埃及金字塔', '日本富士山'] as const;
export const TRAVEL_MODE_OPTIONS: ReadonlyArray<{ id: TravelMode; label: string }> = [
  { id: 'drive', label: '驾车' },
  { id: 'bus', label: '公交' },
  { id: 'walk', label: '步行' },
  { id: 'bike', label: '骑行' },
];

const project2RegionCount = new Set(DESTINATION_POINTS.map((point) => point.region)).size;

export const PROJECT2_METRICS = [
  { label: '覆盖洲别', value: `${project2RegionCount} 大洲` },
  { label: '景点样本', value: String(DESTINATION_POINTS.length) },
  { label: '核心能力', value: '搜索 + 路线 + 预算' },
] as const;

export const PROJECT2_FEATURES = [
  {
    title: 'Three.js 地球浏览',
    description: '支持拖拽旋转、滚轮缩放、视角重置与旋转锁定，贴近 PRD 的核心交互要求。',
  },
  {
    title: '语义搜索与聚焦',
    description: '输入一句话描述即可返回 Top 3 匹配结果，并将视角拉近到目标景点。',
  },
  {
    title: '路线与价格估算',
    description: '基于起点、出行方式和景点成本给出距离、时间和预算区间估算。',
  },
] as const;

export const PROJECT2_PHASE2_NOTES = [
  '若配置真实 API Key，可把路线与景点数据替换成高德与 Geoapify 的实时结果。',
  '当前语义搜索为站内轻量匹配，可继续接入 AI 接口提升复杂描述识别能力。',
  '后续可把收藏、搜索历史和路线分享扩展成更完整的旅行决策工作台。',
] as const;
