export const WORLDSCENE_POI_OVERRIDES = {
  'cloud-gate-chicago': {
    searchTerms: ['Cloud Gate Chicago', 'Cloud Gate Millennium Park', 'The Bean Chicago'],
    domesticSearchTerms: ['芝加哥云门', '云门 千禧公园', 'The Bean Chicago'],
    requiredTerms: ['cloud gate', 'millennium park', 'the bean', '芝加哥', '云门'],
    excludedTerms: ['携程旅行网', 'logo', 'map', 'ticket'],
    preferredMonths: [4, 5, 6, 9, 10],
  },
  'cartagena-old-town': {
    searchTerms: ['Cartagena Old Town Colombia', 'Walled City Cartagena', 'Cartagena de Indias old town'],
    domesticSearchTerms: ['卡塔赫纳老城', '哥伦比亚卡塔赫纳老城', '卡塔赫纳古城'],
    requiredTerms: ['cartagena', 'old town', 'walled city', 'colombia', '卡塔赫纳'],
    excludedTerms: ['携程旅行网', 'logo', 'map', 'ticket'],
    preferredMonths: [1, 2, 3, 12],
  },
  'pamukkale-travertines': {
    searchTerms: ['Pamukkale travertines', 'Pamukkale white terraces', 'Pamukkale Turkey'],
    domesticSearchTerms: ['棉花堡钙华梯田', '棉花堡 白色梯田', '土耳其棉花堡'],
    requiredTerms: ['pamukkale', 'travertines', 'white terraces', '棉花堡', '钙华'],
    excludedTerms: ['hierapolis', '希拉波利斯', 'museum', '遗址博物馆'],
    preferredMonths: [4, 5, 6, 9, 10],
  },
  'dubrovnik-old-town': {
    searchTerms: ['Dubrovnik Old Town', 'Old Town Dubrovnik Croatia', 'Dubrovnik city walls'],
    domesticSearchTerms: ['杜布罗夫尼克老城', '杜布罗夫尼克古城', '克罗地亚杜布罗夫尼克'],
    requiredTerms: ['dubrovnik', 'old town', 'city walls', 'croatia', '杜布罗夫尼克'],
    excludedTerms: ['1667', 'bridge', 'tudjman', 'map', 'painting'],
    preferredMonths: [4, 5, 6, 9, 10],
  },
  'temple-of-heaven-beijing': {
    searchTerms: ['Temple of Heaven Beijing', 'Tiantan Beijing', 'Hall of Prayer for Good Harvests'],
    domesticSearchTerms: ['北京天坛', '天坛公园', '祈年殿'],
    requiredTerms: ['temple of heaven', 'tiantan', '北京天坛', '祈年殿', 'beijing'],
    excludedTerms: ['地坛', '日坛', '月坛', '天坛奖'],
    preferredMonths: [3, 4, 5, 9, 10, 11],
  },
  'summer-palace-beijing': {
    searchTerms: ['Summer Palace Beijing', 'Yiheyuan Beijing', 'Kunming Lake Summer Palace'],
    domesticSearchTerms: ['颐和园', '北京颐和园', '昆明湖 颐和园'],
    requiredTerms: ['summer palace', 'yiheyuan', '颐和园', '昆明湖', 'beijing'],
    excludedTerms: ['圆明园', '避暑山庄', '长春园'],
    preferredMonths: [4, 5, 6, 9, 10],
  },
  petra: {
    searchTerms: ['Petra Jordan', 'Petra Archaeological Park', 'Al-Khazneh Petra'],
    domesticSearchTerms: ['佩特拉古城', '约旦佩特拉', '约旦玫瑰古城'],
    requiredTerms: ['petra', 'jordan', 'wadi musa', '约旦', '佩特拉古城'],
    excludedTerms: ['拉鲁', '人物', '角色', '动画', '演员'],
    preferredMonths: [3, 4, 5, 9, 10, 11],
  },
  'boracay-white-beach': {
    searchTerms: ['Boracay White Beach', 'White Beach Boracay', 'Boracay Station 1 beach'],
    domesticSearchTerms: ['长滩岛白沙滩', '长滩岛 白沙滩', 'Boracay White Beach'],
    requiredTerms: ['boracay', 'white beach', '长滩岛', '白沙滩', '菲律宾'],
    excludedTerms: ['logo', 'map', 'station map', '酒店', '度假村广告', 'puka', 'algal bloom', 'cleanup', 't-shirts shop', 'kitesurfing', 'station map'],
    preferredMonths: [1, 2, 3, 4, 11, 12],
  },
  'grand-canyon': {
    searchTerms: ['Grand Canyon', 'Grand Canyon National Park', 'Arizona Grand Canyon'],
    domesticSearchTerms: ['美国大峡谷', '科罗拉多大峡谷', '亚利桑那大峡谷'],
    requiredTerms: ['grand canyon', 'arizona', '美国大峡谷', '科罗拉多大峡谷', '亚利桑那'],
    excludedTerms: ['恩施', '湖北', '恩施州'],
  },
  'washington-national-mall': {
    searchTerms: ['National Mall Washington DC', 'National Mall', 'Washington Monument Reflecting Pool'],
    domesticSearchTerms: ['华盛顿国家广场', '华盛顿特区国家广场', 'National Mall Washington DC'],
    requiredTerms: ['national mall', 'washington dc', '华盛顿国家广场', '华盛顿特区'],
    excludedTerms: ['纽约', 'washington square', 'new york', '纽约市著名广场'],
  },
  uluru: {
    searchTerms: ['Uluru', 'Uluru Kata Tjuta', 'Ayers Rock', 'Uluru Australia'],
    domesticSearchTerms: ['乌鲁鲁', '艾尔斯岩', '澳大利亚乌鲁鲁', 'Uluru Australia'],
    requiredTerms: ['uluru', 'ayers rock', 'kata tjuta', '澳大利亚', '艾尔斯岩'],
    excludedTerms: ['神魄', '动画', '角色', '动漫', '中国动画'],
    preferredMonths: [4, 5, 6, 7, 8, 9],
  },
  'alhambra-granada': {
    searchTerms: ['Alhambra Granada', 'Alhambra Palace Granada', 'La Alhambra Spain'],
    domesticSearchTerms: ['阿尔罕布拉宫', '西班牙阿尔罕布拉宫', '格拉纳达阿尔罕布拉宫'],
    requiredTerms: ['alhambra', 'granada', '西班牙', '格拉纳达', '阿尔罕布拉'],
    excludedTerms: ['海丰', '红宫', '红场旧址'],
    preferredMonths: [4, 5, 6, 9, 10],
  },
  'mont-saint-michel': {
    searchTerms: ['Mont Saint-Michel', 'Mont-Saint-Michel', 'France Mont Saint-Michel'],
    domesticSearchTerms: ['圣米歇尔山', '法国圣米歇尔山', '圣米歇尔山修道院'],
    requiredTerms: ['mont saint michel', 'mont-saint-michel', '圣米歇尔山', '法国'],
    excludedTerms: ['maquette', '模型', '沙盘', 'plan relief', 'miniature', 'cannon', 'cannons', 'cooke', 'painting', 'draw', 'illustration', 'engraving'],
    preferredMonths: [4, 5, 6, 7, 8, 9, 10],
  },
  plitvice: {
    searchTerms: ['Plitvice Lakes', 'Plitvice Lakes National Park', 'Croatia Plitvice Lakes'],
    domesticSearchTerms: ['十六湖国家公园', '克罗地亚十六湖', '普利特维采湖群国家公园'],
    requiredTerms: ['plitvice', 'croatia', '十六湖', '普利特维采', '克罗地亚'],
    excludedTerms: ['中国', '景区', '度假区'],
    preferredMonths: [5, 6, 7, 8, 9, 10],
  },
  'forbidden-city': {
    searchTerms: ['Forbidden City', 'Palace Museum Beijing', '故宫', '北京故宫'],
    domesticSearchTerms: ['故宫', '北京故宫', '故宫博物院'],
    requiredTerms: ['forbidden city', 'palace museum', '故宫', '紫禁城'],
    excludedTerms: ['map', 'ticket', 'logo'],
  },
  'great-wall': {
    searchTerms: ['Great Wall of China', 'Mutianyu Great Wall', '长城', '慕田峪长城'],
    domesticSearchTerms: ['长城', '北京长城', '慕田峪长城'],
    requiredTerms: ['great wall', '长城'],
  },
  'mount-fuji': {
    searchTerms: ['Mount Fuji', '富士山', 'Lake Kawaguchi Mount Fuji'],
    requiredTerms: ['fuji', '富士'],
    preferredMonths: [11, 12, 1, 2, 3, 4],
  },
  kyoto: {
    searchTerms: ['Kyoto', '京都', 'Kyoto temple'],
    requiredTerms: ['kyoto', '京都'],
    preferredMonths: [3, 4, 5, 10, 11],
  },
  'eiffel-tower': {
    searchTerms: ['Eiffel Tower', 'Tour Eiffel', '埃菲尔铁塔', '巴黎铁塔'],
    domesticSearchTerms: ['埃菲尔铁塔', '巴黎铁塔'],
    requiredTerms: ['eiffel', 'tour eiffel', '铁塔'],
  },
  santorini: {
    searchTerms: ['Santorini', 'Oia Santorini', '圣托里尼', '伊亚'],
    requiredTerms: ['santorini', 'oia', '圣托里尼'],
    preferredMonths: [5, 6, 7, 8, 9],
  },
  reykjavik: {
    searchTerms: ['Reykjavik aurora', 'Reykjavik', '雷克雅未克 极光'],
    requiredTerms: ['reykjavik', '雷克雅未克'],
    preferredMonths: [9, 10, 11, 12, 1, 2, 3],
  },
  'west-lake-hangzhou': {
    searchTerms: ['West Lake Hangzhou', '杭州西湖', 'Hangzhou West Lake'],
    domesticSearchTerms: ['杭州西湖', '西湖 杭州'],
    requiredTerms: ['west lake', 'hangzhou', '西湖'],
    preferredMonths: [3, 4, 5, 9, 10, 11],
  },
  'jiuzhaigou-valley': {
    searchTerms: ['Jiuzhaigou Valley', '九寨沟', 'Jiuzhaigou National Park'],
    domesticSearchTerms: ['九寨沟', '九寨沟风景区'],
    requiredTerms: ['jiuzhaigou', '九寨沟'],
    preferredMonths: [9, 10, 11],
  },
  'huangshan-yellow-mountain': {
    searchTerms: ['Huangshan', 'Yellow Mountain China', '黄山'],
    domesticSearchTerms: ['黄山', '黄山风景区'],
    requiredTerms: ['huangshan', 'yellow mountain', '黄山'],
    preferredMonths: [4, 5, 9, 10, 11],
  },
  'potala-palace-lhasa': {
    searchTerms: ['Potala Palace', '布达拉宫', 'Potala Palace Lhasa'],
    domesticSearchTerms: ['布达拉宫', '拉萨布达拉宫'],
    requiredTerms: ['potala', '布达拉宫'],
    preferredMonths: [5, 6, 7, 8, 9, 10],
  },
  'kanas-lake-scenic': {
    searchTerms: ['Kanas Lake', '喀纳斯湖', 'Kanas Xinjiang'],
    domesticSearchTerms: ['喀纳斯', '新疆喀纳斯'],
    requiredTerms: ['kanas', '喀纳斯'],
    preferredMonths: [9, 10],
  },
  'heaven-lake-changbai': {
    searchTerms: ['Changbai Mountain Tianchi', 'Heaven Lake Changbai', '长白山天池'],
    domesticSearchTerms: ['长白山天池', '长白山'],
    requiredTerms: ['changbai', 'heaven lake', '天池', '长白山'],
    preferredMonths: [6, 7, 8, 9],
  },
  'yading-nature-reserve': {
    searchTerms: ['Yading Nature Reserve', 'Daocheng Yading', '稻城亚丁'],
    domesticSearchTerms: ['稻城亚丁', '亚丁自然保护区'],
    requiredTerms: ['yading', 'daocheng', '亚丁', '稻城'],
    preferredMonths: [9, 10],
  },
};
